/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.SizeTwoRich
import Mathlib.Tactic.FinCases

/-! # One-credit rich catalogue block 05

Generated by scripts/import_size_two_rich.py from SHA256 943309a1cd4fafcbe0c4f70825b5fe92dd920134337011be917a0ada47d52bda.
Literal witness acceptance only; actual-state coverage and transport are separate.
-/
namespace Gallai.Certificate.SizeTwo.Rich.Catalogue.Block05
open Star.Vertex
set_option maxRecDepth 100000
set_option maxHeartbeats 0

/-- Literal state from the pinned source. -/
def state : Fin 15 → State :=
  ![![5,0,15,6,15],
    ![5,3,3,9,15],
    ![5,3,3,10,12],
    ![5,3,5,9,9],
    ![5,3,5,10,10],
    ![5,3,5,12,12],
    ![5,3,5,15,15],
    ![5,3,6,9,10],
    ![5,3,6,12,15],
    ![5,3,9,3,15],
    ![5,3,9,5,9],
    ![5,3,9,6,10],
    ![5,3,10,3,12],
    ![5,3,10,5,10],
    ![5,3,10,6,9]]

/-- Literal special from the pinned source. -/
def special : Fin 15 → Fin 4 → Bool :=
  ![![false,
    false,
    false,
    false],
    ![false,
    false,
    false,
    false],
    ![false,
    false,
    false,
    false],
    ![false,
    false,
    false,
    false],
    ![false,
    false,
    false,
    false],
    ![false,
    false,
    false,
    false],
    ![false,
    false,
    false,
    false],
    ![false,
    false,
    false,
    false],
    ![false,
    false,
    false,
    false],
    ![false,
    false,
    false,
    false],
    ![false,
    false,
    false,
    false],
    ![false,
    false,
    false,
    false],
    ![false,
    false,
    false,
    false],
    ![false,
    false,
    false,
    false],
    ![false,
    false,
    false,
    false]]

/-- Literal words from the pinned source. -/
def words : Fin 15 → Fin 4 → Fin 4 → List Star.Vertex :=
  ![![![[p, b, r],
    [q, c, r],
    [r, d, x, a],
    []],
    ![[p, b, s],
    [q, b, x, d, s],
    [],
    []],
    ![[p, b, r],
    [],
    [],
    [r, d, x, a]],
    ![[p, b, s],
    [],
    [],
    [s, d, x, a]]],
    ![![[p, d, r],
    [q, a, x, r],
    [],
    []],
    ![[p, c, s],
    [q, a, x, d, s],
    [],
    []],
    ![[p, d, r],
    [],
    [],
    [r, x, a]],
    ![[p, c, s],
    [],
    [],
    [s, d, x, a]]],
    ![![[p, x, r],
    [q, c, d, r],
    [],
    []],
    ![[p, x, c, s],
    [q, c, d, s],
    [],
    []],
    ![[p, x, r],
    [],
    [],
    []],
    ![[p, x, c, s],
    [],
    [],
    []]],
    ![![[p, b, r],
    [q, a, x, r],
    [],
    []],
    ![[p, c, s],
    [q, a, x, d, s],
    [],
    []],
    ![[p, b, r],
    [],
    [],
    [r, x, a]],
    ![[p, c, s],
    [],
    [],
    [s, d, x, a]]],
    ![![[p, b, r],
    [q, a, x, r],
    [],
    []],
    ![[p, x, c, s],
    [q, d, s],
    [],
    []],
    ![[p, b, r],
    [],
    [],
    [r, x, a]],
    ![[p, x, c, s],
    [],
    [],
    []]],
    ![![[p, b, r],
    [q, a, x, r],
    [],
    []],
    ![[p, x, c, s],
    [q, a, x, d, s],
    [],
    []],
    ![[p, b, r],
    [],
    [],
    [r, x, a]],
    ![[p, x, c, s],
    [],
    [],
    []]],
    ![![[p, b, r],
    [q, c, r],
    [r, d, x, a],
    []],
    ![[p, c, s],
    [q, a, x, d, s],
    [],
    []],
    ![[p, b, r],
    [],
    [],
    [r, c, d, x, a]],
    ![[p, c, s],
    [],
    [],
    [s, d, c, x, a]]],
    ![![[p, x, r],
    [q, b, r],
    [],
    []],
    ![[p, c, s],
    [q, a, x, d, s],
    [],
    []],
    ![[p, x, r],
    [],
    [],
    []],
    ![[p, c, s],
    [],
    [],
    [s, d, x, a]]],
    ![![[p, d, r],
    [q, b, r],
    [r, x, a],
    []],
    ![[p, d, s],
    [q, a, x, c, s],
    [],
    []],
    ![[p, d, r],
    [],
    [],
    [r, x, a]],
    ![[p, d, s],
    [],
    [],
    [s, c, x, a]]],
    ![![[p, d, r],
    [q, a, x, r],
    [],
    []],
    ![[p, b, s],
    [q, a, x, d, s],
    [],
    []],
    ![[p, d, r],
    [],
    [],
    [r, x, a]],
    ![[p, b, s],
    [],
    [],
    [s, d, x, a]]],
    ![![[p, c, r],
    [q, a, x, r],
    [],
    []],
    ![[p, b, s],
    [q, a, x, d, s],
    [],
    []],
    ![[p, c, r],
    [],
    [],
    [r, x, a]],
    ![[p, b, s],
    [],
    [],
    [s, d, x, a]]],
    ![![[p, x, r],
    [q, c, r],
    [],
    []],
    ![[p, b, s],
    [q, a, x, d, s],
    [],
    []],
    ![[p, x, r],
    [],
    [],
    []],
    ![[p, b, s],
    [],
    [],
    [s, d, x, a]]],
    ![![[p, x, r],
    [q, c, d, r],
    [],
    []],
    ![[p, a, b, s],
    [q, a, x, d, s],
    [],
    []],
    ![[p, x, r],
    [],
    [],
    []],
    ![[p, a, b, s],
    [],
    [],
    [s, d, x, a]]],
    ![![[p, c, r],
    [q, a, x, r],
    [],
    []],
    ![[p, a, b, s],
    [q, a, x, d, s],
    [],
    []],
    ![[p, c, r],
    [],
    [],
    [r, x, a]],
    ![[p, a, b, s],
    [],
    [],
    [s, d, x, a]]],
    ![![[p, x, r],
    [q, c, r],
    [],
    []],
    ![[p, d, s],
    [q, a, x, b, s],
    [],
    []],
    ![[p, x, r],
    [],
    [],
    []],
    ![[p, d, s],
    [],
    [],
    [s, b, x, a]]]]

/-- Literal added from the pinned source. -/
def added : Fin 15 → Fin 4 → List (List Star.Vertex) :=
  ![![[[a, b, x, c, d, q], [q, b, s, d, p, x, r]],
    [[a, b, r, d, c, x, p], [a, x, r, c, q, d, p]],
    [[a, b, q, d, c, x, p], [p, d, s, b, x, r, c, q]],
    [[a, b, q, c, x, r, d, p], [p, x, b, r, c, d, q]]],
    ![[[a, b, p, c, x, d, s], [a, p, x, b, q, d, c, s]],
    [[a, b, x, p, d, c], [a, p, b, q, d, r, x, c]],
    [[a, b, q, d, x, p, c, s], [q, a, p, b, x, c, d, s]],
    [[a, b, q, d, p, x, c], [c, d, r, x, b, p, a, q]]],
    ![[[c, x, a, b, p], [c, s, d, x, b, q, a, p]],
    [[d, x, a, b, p], [d, r, x, b, q, a, p]],
    [[p, a, b, x, d, c, q], [p, b, q, a, x, c, s, d, r]],
    [[c, d, x, a, b, q], [c, q, a, p, b, x, r, d, s]]],
    ![[[a, b, x, c, p, d, s], [a, p, x, d, c, s]],
    [[a, b, p, x, r], [a, p, d, c, x, b, r]],
    [[a, b, x, c, p, d, s], [q, a, p, x, d, c, s]],
    [[a, b, p, x, r], [q, a, p, d, c, x, b, r]]],
    ![[[a, b, x, c, d, q], [a, p, x, d, s, c, q]],
    [[d, x, a, b, r], [d, c, q, a, p, b, x, r]],
    [[a, b, x, c, q, d, s], [q, a, p, x, d, c, s]],
    [[p, a, b, x, d, q], [p, b, r, x, a, q, c, d, s]]],
    ![[[a, b, x, c, d, r], [a, p, x, d, s, c, r]],
    [[a, b, r, c], [a, p, b, x, r, d, c]],
    [[a, b, x, c, d, r], [q, a, p, x, d, s, c, r]],
    [[c, d, r, x, b, a, q], [c, r, b, p, a, x, d, s]]],
    ![[[a, b, x, c, p, d, s], [r, x, p, a, q, d, c, s]],
    [[a, b, p, d, r, x, c, q], [a, p, x, b, r, c, d, q]],
    [[a, b, x, p, c, q, d, r], [q, a, p, d, s, c, x, r]],
    [[a, b, p, x, r, d, q, c], [c, r, b, x, d, p, a, q]]],
    ![[[b, a, x, c, d, q], [b, x, d, s, c, p, a, q]],
    [[a, b, x, c], [a, p, x, r, b, q, d, c]],
    [[p, a, b, x, c, d, q], [p, c, s, d, x, a, q, b, r]],
    [[c, x, b, a, q], [a, p, x, r, b, q, d, c]]],
    ![[[a, b, x, c, d, q], [q, a, p, x, d, s, c, r]],
    [[a, b, r, x, d, c], [a, p, x, b, q, d, r, c]],
    [[a, b, q, d, x, c, s], [q, a, p, x, b, r, c, d, s]],
    [[a, b, q, d, x, r, c], [c, d, r, b, x, p, a, q]]],
    ![[[a, b, p, c, x, d, q], [a, p, x, b, s, d, c, q]],
    [[a, b, x, c, p, d, q], [a, p, x, r, d, c, q]],
    [[a, b, p, x, c, q, d, s], [q, a, p, c, d, x, b, s]],
    [[b, a, p, x, c, d, q], [a, q, c, p, d, r, x, b]]],
    ![[[a, b, p, d, x, c], [a, p, x, b, s, d, c]],
    [[a, b, x, c, p, d], [a, p, x, r, c, d]],
    [[a, b, p, d, x, c], [c, d, s, b, x, p, a, q]],
    [[a, b, x, c, p, d], [d, c, r, x, p, a, q]]],
    ![[[c, d, x, a, b, p], [c, x, b, s, d, q, a, p]],
    [[a, b, x, c, d], [a, p, x, r, c, q, d]],
    [[p, a, b, x, c, d, q], [p, b, s, d, x, a, q, c, r]],
    [[a, b, x, c, q, d], [d, c, r, x, p, a, q]]],
    ![[[c, x, a, b, s], [c, p, a, q, b, x, d, s]],
    [[b, q, c, x, p], [b, x, r, d, c, p]],
    [[p, a, b, x, d, c, q], [p, c, x, a, q, b, s, d, r]],
    [[a, q, c, x, p], [p, c, d, r, x, b, q]]],
    ![[[a, b, x, d, q], [a, p, x, c, d, s, b, q]],
    [[p, c, x, b, q], [p, x, r, c, d, q]],
    [[a, b, q, d, x, c], [c, d, s, b, x, p, a, q]],
    [[a, q, b, x, c, p], [p, x, r, c, d, q]]],
    ![[[c, d, x, a, b, q], [c, x, b, s, d, p, a, q]],
    [[a, b, q, c, x, d], [a, p, x, r, c, d]],
    [[p, a, b, x, d, c, q], [p, d, s, b, q, a, x, c, r]],
    [[a, b, q, c, x, d], [d, c, r, x, p, a, q]]]]

/-- Every record satisfies the contract for its actual reconstruction kind. -/
private theorem accepted_row_000 (i : Fin 4) :
    if special (0 : Fin 15) i then SeparatedAccepted (state (0 : Fin 15)) i (words (0 : Fin 15) i 0) (words (0 : Fin 15) i 1) (added (0 : Fin 15) i)
    else AcceptedRecord (state (0 : Fin 15)) i (words (0 : Fin 15) i) (added (0 : Fin 15) i) := by
  fin_cases i <;> decide

private theorem accepted_row_001 (i : Fin 4) :
    if special (1 : Fin 15) i then SeparatedAccepted (state (1 : Fin 15)) i (words (1 : Fin 15) i 0) (words (1 : Fin 15) i 1) (added (1 : Fin 15) i)
    else AcceptedRecord (state (1 : Fin 15)) i (words (1 : Fin 15) i) (added (1 : Fin 15) i) := by
  fin_cases i <;> decide

private theorem accepted_row_002 (i : Fin 4) :
    if special (2 : Fin 15) i then SeparatedAccepted (state (2 : Fin 15)) i (words (2 : Fin 15) i 0) (words (2 : Fin 15) i 1) (added (2 : Fin 15) i)
    else AcceptedRecord (state (2 : Fin 15)) i (words (2 : Fin 15) i) (added (2 : Fin 15) i) := by
  fin_cases i <;> decide

private theorem accepted_row_003 (i : Fin 4) :
    if special (3 : Fin 15) i then SeparatedAccepted (state (3 : Fin 15)) i (words (3 : Fin 15) i 0) (words (3 : Fin 15) i 1) (added (3 : Fin 15) i)
    else AcceptedRecord (state (3 : Fin 15)) i (words (3 : Fin 15) i) (added (3 : Fin 15) i) := by
  fin_cases i <;> decide

private theorem accepted_row_004 (i : Fin 4) :
    if special (4 : Fin 15) i then SeparatedAccepted (state (4 : Fin 15)) i (words (4 : Fin 15) i 0) (words (4 : Fin 15) i 1) (added (4 : Fin 15) i)
    else AcceptedRecord (state (4 : Fin 15)) i (words (4 : Fin 15) i) (added (4 : Fin 15) i) := by
  fin_cases i <;> decide

private theorem accepted_row_005 (i : Fin 4) :
    if special (5 : Fin 15) i then SeparatedAccepted (state (5 : Fin 15)) i (words (5 : Fin 15) i 0) (words (5 : Fin 15) i 1) (added (5 : Fin 15) i)
    else AcceptedRecord (state (5 : Fin 15)) i (words (5 : Fin 15) i) (added (5 : Fin 15) i) := by
  fin_cases i <;> decide

private theorem accepted_row_006 (i : Fin 4) :
    if special (6 : Fin 15) i then SeparatedAccepted (state (6 : Fin 15)) i (words (6 : Fin 15) i 0) (words (6 : Fin 15) i 1) (added (6 : Fin 15) i)
    else AcceptedRecord (state (6 : Fin 15)) i (words (6 : Fin 15) i) (added (6 : Fin 15) i) := by
  fin_cases i <;> decide

private theorem accepted_row_007 (i : Fin 4) :
    if special (7 : Fin 15) i then SeparatedAccepted (state (7 : Fin 15)) i (words (7 : Fin 15) i 0) (words (7 : Fin 15) i 1) (added (7 : Fin 15) i)
    else AcceptedRecord (state (7 : Fin 15)) i (words (7 : Fin 15) i) (added (7 : Fin 15) i) := by
  fin_cases i <;> decide

private theorem accepted_row_008 (i : Fin 4) :
    if special (8 : Fin 15) i then SeparatedAccepted (state (8 : Fin 15)) i (words (8 : Fin 15) i 0) (words (8 : Fin 15) i 1) (added (8 : Fin 15) i)
    else AcceptedRecord (state (8 : Fin 15)) i (words (8 : Fin 15) i) (added (8 : Fin 15) i) := by
  fin_cases i <;> decide

private theorem accepted_row_009 (i : Fin 4) :
    if special (9 : Fin 15) i then SeparatedAccepted (state (9 : Fin 15)) i (words (9 : Fin 15) i 0) (words (9 : Fin 15) i 1) (added (9 : Fin 15) i)
    else AcceptedRecord (state (9 : Fin 15)) i (words (9 : Fin 15) i) (added (9 : Fin 15) i) := by
  fin_cases i <;> decide

private theorem accepted_row_010 (i : Fin 4) :
    if special (10 : Fin 15) i then SeparatedAccepted (state (10 : Fin 15)) i (words (10 : Fin 15) i 0) (words (10 : Fin 15) i 1) (added (10 : Fin 15) i)
    else AcceptedRecord (state (10 : Fin 15)) i (words (10 : Fin 15) i) (added (10 : Fin 15) i) := by
  fin_cases i <;> decide

private theorem accepted_row_011 (i : Fin 4) :
    if special (11 : Fin 15) i then SeparatedAccepted (state (11 : Fin 15)) i (words (11 : Fin 15) i 0) (words (11 : Fin 15) i 1) (added (11 : Fin 15) i)
    else AcceptedRecord (state (11 : Fin 15)) i (words (11 : Fin 15) i) (added (11 : Fin 15) i) := by
  fin_cases i <;> decide

private theorem accepted_row_012 (i : Fin 4) :
    if special (12 : Fin 15) i then SeparatedAccepted (state (12 : Fin 15)) i (words (12 : Fin 15) i 0) (words (12 : Fin 15) i 1) (added (12 : Fin 15) i)
    else AcceptedRecord (state (12 : Fin 15)) i (words (12 : Fin 15) i) (added (12 : Fin 15) i) := by
  fin_cases i <;> decide

private theorem accepted_row_013 (i : Fin 4) :
    if special (13 : Fin 15) i then SeparatedAccepted (state (13 : Fin 15)) i (words (13 : Fin 15) i 0) (words (13 : Fin 15) i 1) (added (13 : Fin 15) i)
    else AcceptedRecord (state (13 : Fin 15)) i (words (13 : Fin 15) i) (added (13 : Fin 15) i) := by
  fin_cases i <;> decide

private theorem accepted_row_014 (i : Fin 4) :
    if special (14 : Fin 15) i then SeparatedAccepted (state (14 : Fin 15)) i (words (14 : Fin 15) i 0) (words (14 : Fin 15) i 1) (added (14 : Fin 15) i)
    else AcceptedRecord (state (14 : Fin 15)) i (words (14 : Fin 15) i) (added (14 : Fin 15) i) := by
  fin_cases i <;> decide

theorem accepted (o : Fin 15) (i : Fin 4) :
    if special o i then SeparatedAccepted (state o) i (words o i 0) (words o i 1) (added o i)
    else AcceptedRecord (state o) i (words o i) (added o i) := by
  fin_cases o
  · exact accepted_row_000 i
  · exact accepted_row_001 i
  · exact accepted_row_002 i
  · exact accepted_row_003 i
  · exact accepted_row_004 i
  · exact accepted_row_005 i
  · exact accepted_row_006 i
  · exact accepted_row_007 i
  · exact accepted_row_008 i
  · exact accepted_row_009 i
  · exact accepted_row_010 i
  · exact accepted_row_011 i
  · exact accepted_row_012 i
  · exact accepted_row_013 i
  · exact accepted_row_014 i


end Gallai.Certificate.SizeTwo.Rich.Catalogue.Block05
