/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.SizeTwoRich
import Mathlib.Tactic.FinCases

/-! # One-credit rich catalogue block 03

Generated by scripts/import_size_two_rich.py from SHA256 943309a1cd4fafcbe0c4f70825b5fe92dd920134337011be917a0ada47d52bda.
Literal witness acceptance only; actual-state coverage and transport are separate.
-/
namespace Gallai.Certificate.SizeTwo.Rich.Catalogue.Block03
open Star.Vertex
set_option maxRecDepth 100000
set_option maxHeartbeats 0

/-- Literal state from the pinned source. -/
def state : Fin 15 → State :=
  ![![3,5,9,5,9],
    ![3,5,9,6,10],
    ![3,5,10,5,10],
    ![3,5,10,6,9],
    ![3,5,12,5,12],
    ![3,5,12,6,15],
    ![3,5,15,5,15],
    ![3,12,12,12,12],
    ![3,12,12,15,15],
    ![3,12,15,12,15],
    ![3,15,15,15,15],
    ![5,0,3,9,12],
    ![5,0,3,10,15],
    ![5,0,5,9,10],
    ![5,0,5,12,15]]

/-- Literal special from the pinned source. -/
def special : Fin 15 → Fin 4 → Bool :=
  ![![false,
    false,
    false,
    false],
    ![false,
    false,
    false,
    false],
    ![false,
    false,
    false,
    false],
    ![false,
    false,
    false,
    false],
    ![false,
    false,
    false,
    false],
    ![false,
    false,
    false,
    false],
    ![false,
    false,
    false,
    false],
    ![false,
    false,
    false,
    false],
    ![false,
    false,
    false,
    false],
    ![false,
    false,
    false,
    false],
    ![false,
    false,
    false,
    false],
    ![false,
    false,
    false,
    false],
    ![false,
    false,
    false,
    false],
    ![false,
    false,
    false,
    false],
    ![false,
    false,
    false,
    false]]

/-- Literal words from the pinned source. -/
def words : Fin 15 → Fin 4 → Fin 4 → List Star.Vertex :=
  ![![![[p, a, r],
    [q, x, c, r],
    [],
    []],
    ![[p, b, s],
    [q, x, d, s],
    [],
    []],
    ![[p, a, r],
    [],
    [],
    [r, c, x, a]],
    ![[p, b, s],
    [],
    [],
    [s, d, x, a]]],
    ![![[p, a, r],
    [q, x, c, r],
    [],
    []],
    ![[p, b, s],
    [q, x, d, s],
    [],
    []],
    ![[p, a, r],
    [],
    [],
    [r, c, x, a]],
    ![[p, b, s],
    [],
    [],
    [s, d, x, a]]],
    ![![[p, a, r],
    [q, x, c, r],
    [],
    []],
    ![[p, a, b, s],
    [q, x, d, s],
    [],
    []],
    ![[p, a, r],
    [],
    [],
    [r, c, x, a]],
    ![[p, a, b, s],
    [],
    [],
    [s, d, x, a]]],
    ![![[p, a, r],
    [q, x, c, r],
    [],
    []],
    ![[p, d, s],
    [q, x, b, s],
    [],
    []],
    ![[p, a, r],
    [],
    [],
    [r, c, x, a]],
    ![[p, d, s],
    [],
    [],
    [s, b, x, a]]],
    ![![[p, a, r],
    [q, x, b, r],
    [],
    []],
    ![[p, a, b, s],
    [q, x, d, s],
    [],
    []],
    ![[p, a, r],
    [],
    [],
    [r, b, x, a]],
    ![[p, a, b, s],
    [],
    [],
    [s, d, x, a]]],
    ![![[p, a, r],
    [q, c, r],
    [r, d, x, a],
    []],
    ![[p, d, s],
    [q, x, b, s],
    [],
    []],
    ![[p, a, r],
    [],
    [],
    [r, d, x, a]],
    ![[p, d, s],
    [],
    [],
    [s, b, x, a]]],
    ![![[p, a, r],
    [q, b, r],
    [r, d, x, a],
    []],
    ![[p, b, s],
    [q, b, x, d, s],
    [],
    []],
    ![[p, a, r],
    [],
    [],
    [r, b, x, d, c]],
    ![[p, b, s],
    [],
    [],
    [s, d, c, x, a]]],
    ![![[p, x, a, r],
    [q, x, b, r],
    [],
    []],
    ![[p, x, a, s],
    [q, x, b, s],
    [],
    []],
    ![[p, x, a, r],
    [],
    [],
    []],
    ![[p, x, a, s],
    [],
    [],
    []]],
    ![![[p, c, r],
    [q, d, r],
    [r, a, x, b],
    []],
    ![[p, c, s],
    [q, d, s],
    [s, a, x, b],
    []],
    ![[p, c, r],
    [],
    [],
    [r, d, x, a]],
    ![[p, c, s],
    [],
    [],
    [s, d, x, a]]],
    ![![[p, b, r],
    [q, d, r],
    [r, a, x, b],
    []],
    ![[p, b, s],
    [q, d, s],
    [s, a, x, b],
    []],
    ![[p, b, r],
    [],
    [],
    [r, d, x, a]],
    ![[p, b, s],
    [],
    [],
    [s, d, x, a]]],
    ![![[p, a, r],
    [q, b, r],
    [r, c, d, x, a, b],
    []],
    ![[p, a, s],
    [q, b, s],
    [s, c, d, x, a, b],
    []],
    ![[p, a, r],
    [q, a],
    [],
    [r, c, d, x, b, a]],
    ![[p, a, s],
    [q, a],
    [],
    [s, c, d, x, b, a]]],
    ![![[p, x, r],
    [q, b, x, d, r],
    [],
    []],
    ![[p, c, s],
    [q, b, x, d, s],
    [],
    []],
    ![[p, x, r],
    [],
    [],
    []],
    ![[p, c, s],
    [],
    [],
    [s, d, x, a]]],
    ![![[p, d, r],
    [q, b, x, r],
    [],
    []],
    ![[p, d, s],
    [q, b, x, c, s],
    [],
    []],
    ![[p, d, r],
    [],
    [],
    [r, x, a]],
    ![[p, d, s],
    [],
    [],
    [s, c, x, a]]],
    ![![[p, b, r],
    [q, d, x, r],
    [],
    []],
    ![[p, c, d, s],
    [q, d, x, c, s],
    [],
    []],
    ![[p, b, r],
    [],
    [],
    [r, x, a]],
    ![[p, c, s],
    [],
    [],
    [s, d, x, a]]],
    ![![[p, b, r],
    [q, d, r],
    [r, x, a],
    []],
    ![[p, d, s],
    [q, d, x, c, s],
    [],
    []],
    ![[p, b, r],
    [],
    [],
    [r, d, x, a]],
    ![[p, d, s],
    [],
    [],
    [s, c, x, a]]]]

/-- Literal added from the pinned source. -/
def added : Fin 15 → Fin 4 → List (List Star.Vertex) :=
  ![![[[a, b, p, x, d, c], [a, x, b, s, d, p, c]],
    [[b, a, p, x, c, d], [b, x, a, r, c, p, d]],
    [[a, b, p, x, d, c], [c, p, d, s, b, x, q]],
    [[a, b, x, c, p, d], [d, c, r, a, p, x, q]]],
    ![[[a, b, x, d, c], [a, x, p, b, s, d, q, c]],
    [[b, a, x, c, d], [b, x, p, a, r, c, q, d]],
    [[a, b, x, d, q, c], [c, d, s, b, p, x, q]],
    [[a, b, x, c, q, d], [d, c, r, a, p, x, q]]],
    ![[[a, b, x, d, q], [a, x, p, c, d, s, b, q]],
    [[a, r, c, x, b], [a, x, p, c, d, q, b]],
    [[a, b, q, d, x, p], [p, c, d, s, b, x, q]],
    [[a, r, c, x, q, b], [b, x, p, c, d, q]]],
    ![[[a, b, x, d, c], [a, x, p, d, s, b, q, c]],
    [[b, a, x, c, d], [b, q, c, r, a, p, x, d]],
    [[a, b, q, x, d, p], [p, x, b, s, d, c, q]],
    [[a, b, q, c, x, d], [d, c, r, a, p, x, q]]],
    ![[[b, a, x, c, d, r], [b, s, d, x, p, c, r]],
    [[a, r, c, x, b], [a, x, p, c, d, r, b]],
    [[a, b, s, d, c, x, p], [p, c, r, d, x, q]],
    [[a, r, c, x, b], [b, r, d, c, p, x, q]]],
    ![[[a, b, x, c, d, p], [p, x, q, d, s, b, r]],
    [[b, a, r, c, d, x, p], [b, r, d, q, c, x, a, p]],
    [[a, b, x, c, q, d, s], [q, x, p, d, c, r, b, s]],
    [[b, a, r, c, d, x, q], [a, p, x, c, q, d, r, b]]],
    ![[[a, b, p, d, c, x, q], [q, d, s, b, x, p, c, r]],
    [[b, a, p, d, r, c, x, q], [b, r, a, x, p, c, d, q]],
    [[a, b, p, d, q, x, c], [a, x, p, c, r, d, s, b, q]],
    [[a, b, q, x, p, d, r, c], [c, p, a, r, b, x, d, q]]],
    ![[[a, b, s, c, d, r], [a, s, d, x, c, r]],
    [[a, b, r, c, d, s], [a, r, d, x, c, s]],
    [[a, b, s, c, x, d, r], [a, s, d, c, r, b, x, q]],
    [[a, b, r, c, x, d, s], [a, r, d, c, s, b, x, q]]],
    ![[[b, a, s, c, d, x, q], [q, c, x, p, d, s, b, r]],
    [[b, a, r, c, d, x, q], [q, c, x, p, d, r, b, s]],
    [[a, b, s, c, d, q, x, p], [p, d, s, a, r, b, x, c, q]],
    [[a, b, r, c, d, q, x, p], [p, d, r, a, s, b, x, c, q]]],
    ![[[a, b, s, d, x, c, r], [a, s, c, d, p, x, q, b]],
    [[a, b, r, d, x, c, s], [a, r, c, d, p, x, q, b]],
    [[a, b, q, d, s, c, x, p], [p, d, c, r, a, s, b, x, q]],
    [[a, b, q, d, r, c, x, p], [p, d, c, s, a, r, b, x, q]]],
    ![[[a, q, c, s, d, p, x, b], [a, s, b, p, c, x, q, d, r]],
    [[a, q, c, r, d, p, x, b], [a, r, b, p, c, x, q, d, s]],
    [[a, s, b, p, c, x, q, d, r], [a, x, p, d, s, c, q, b, r]],
    [[a, r, b, p, c, x, q, d, s], [a, x, p, d, r, c, q, b, s]]],
    ![[[a, b, p, c, d], [a, x, c, s, d]],
    [[b, a, x, c], [b, p, x, r, d, c]],
    [[a, b, x, c, d, r], [a, x, d, s, c, p, b, q]],
    [[a, b, x, c], [c, d, r, x, p, b, q]]],
    ![[[b, a, x, c, d, q], [b, p, x, d, s, c, q]],
    [[b, a, x, d, c], [b, p, x, r, d, q, c]],
    [[a, b, q, c, d, x, p], [p, b, x, c, s, d, q]],
    [[a, b, q, d, x, p], [p, b, x, r, d, c, q]]],
    ![[[a, b, x, c, d], [a, x, p, c, s, d]],
    [[a, b, x, p], [a, x, r, b, p]],
    [[a, b, x, c, d, s], [q, d, x, p, c, s]],
    [[a, b, x, p], [p, b, r, x, c, d, q]]],
    ![[[a, b, x, c, d, p], [p, x, d, s, c, r]],
    [[a, b, x, r, c], [a, x, p, b, r, d, c]],
    [[a, b, x, c, d, p], [p, x, r, c, s, d, q]],
    [[a, b, r, d, x, p], [p, b, x, r, c, d, q]]]]

/-- Every record satisfies the contract for its actual reconstruction kind. -/
private theorem accepted_row_000 (i : Fin 4) :
    if special (0 : Fin 15) i then SeparatedAccepted (state (0 : Fin 15)) i (words (0 : Fin 15) i 0) (words (0 : Fin 15) i 1) (added (0 : Fin 15) i)
    else AcceptedRecord (state (0 : Fin 15)) i (words (0 : Fin 15) i) (added (0 : Fin 15) i) := by
  fin_cases i <;> decide

private theorem accepted_row_001 (i : Fin 4) :
    if special (1 : Fin 15) i then SeparatedAccepted (state (1 : Fin 15)) i (words (1 : Fin 15) i 0) (words (1 : Fin 15) i 1) (added (1 : Fin 15) i)
    else AcceptedRecord (state (1 : Fin 15)) i (words (1 : Fin 15) i) (added (1 : Fin 15) i) := by
  fin_cases i <;> decide

private theorem accepted_row_002 (i : Fin 4) :
    if special (2 : Fin 15) i then SeparatedAccepted (state (2 : Fin 15)) i (words (2 : Fin 15) i 0) (words (2 : Fin 15) i 1) (added (2 : Fin 15) i)
    else AcceptedRecord (state (2 : Fin 15)) i (words (2 : Fin 15) i) (added (2 : Fin 15) i) := by
  fin_cases i <;> decide

private theorem accepted_row_003 (i : Fin 4) :
    if special (3 : Fin 15) i then SeparatedAccepted (state (3 : Fin 15)) i (words (3 : Fin 15) i 0) (words (3 : Fin 15) i 1) (added (3 : Fin 15) i)
    else AcceptedRecord (state (3 : Fin 15)) i (words (3 : Fin 15) i) (added (3 : Fin 15) i) := by
  fin_cases i <;> decide

private theorem accepted_row_004 (i : Fin 4) :
    if special (4 : Fin 15) i then SeparatedAccepted (state (4 : Fin 15)) i (words (4 : Fin 15) i 0) (words (4 : Fin 15) i 1) (added (4 : Fin 15) i)
    else AcceptedRecord (state (4 : Fin 15)) i (words (4 : Fin 15) i) (added (4 : Fin 15) i) := by
  fin_cases i <;> decide

private theorem accepted_row_005 (i : Fin 4) :
    if special (5 : Fin 15) i then SeparatedAccepted (state (5 : Fin 15)) i (words (5 : Fin 15) i 0) (words (5 : Fin 15) i 1) (added (5 : Fin 15) i)
    else AcceptedRecord (state (5 : Fin 15)) i (words (5 : Fin 15) i) (added (5 : Fin 15) i) := by
  fin_cases i <;> decide

private theorem accepted_row_006 (i : Fin 4) :
    if special (6 : Fin 15) i then SeparatedAccepted (state (6 : Fin 15)) i (words (6 : Fin 15) i 0) (words (6 : Fin 15) i 1) (added (6 : Fin 15) i)
    else AcceptedRecord (state (6 : Fin 15)) i (words (6 : Fin 15) i) (added (6 : Fin 15) i) := by
  fin_cases i <;> decide

private theorem accepted_row_007 (i : Fin 4) :
    if special (7 : Fin 15) i then SeparatedAccepted (state (7 : Fin 15)) i (words (7 : Fin 15) i 0) (words (7 : Fin 15) i 1) (added (7 : Fin 15) i)
    else AcceptedRecord (state (7 : Fin 15)) i (words (7 : Fin 15) i) (added (7 : Fin 15) i) := by
  fin_cases i <;> decide

private theorem accepted_row_008 (i : Fin 4) :
    if special (8 : Fin 15) i then SeparatedAccepted (state (8 : Fin 15)) i (words (8 : Fin 15) i 0) (words (8 : Fin 15) i 1) (added (8 : Fin 15) i)
    else AcceptedRecord (state (8 : Fin 15)) i (words (8 : Fin 15) i) (added (8 : Fin 15) i) := by
  fin_cases i <;> decide

private theorem accepted_row_009 (i : Fin 4) :
    if special (9 : Fin 15) i then SeparatedAccepted (state (9 : Fin 15)) i (words (9 : Fin 15) i 0) (words (9 : Fin 15) i 1) (added (9 : Fin 15) i)
    else AcceptedRecord (state (9 : Fin 15)) i (words (9 : Fin 15) i) (added (9 : Fin 15) i) := by
  fin_cases i <;> decide

private theorem accepted_row_010 (i : Fin 4) :
    if special (10 : Fin 15) i then SeparatedAccepted (state (10 : Fin 15)) i (words (10 : Fin 15) i 0) (words (10 : Fin 15) i 1) (added (10 : Fin 15) i)
    else AcceptedRecord (state (10 : Fin 15)) i (words (10 : Fin 15) i) (added (10 : Fin 15) i) := by
  fin_cases i <;> decide

private theorem accepted_row_011 (i : Fin 4) :
    if special (11 : Fin 15) i then SeparatedAccepted (state (11 : Fin 15)) i (words (11 : Fin 15) i 0) (words (11 : Fin 15) i 1) (added (11 : Fin 15) i)
    else AcceptedRecord (state (11 : Fin 15)) i (words (11 : Fin 15) i) (added (11 : Fin 15) i) := by
  fin_cases i <;> decide

private theorem accepted_row_012 (i : Fin 4) :
    if special (12 : Fin 15) i then SeparatedAccepted (state (12 : Fin 15)) i (words (12 : Fin 15) i 0) (words (12 : Fin 15) i 1) (added (12 : Fin 15) i)
    else AcceptedRecord (state (12 : Fin 15)) i (words (12 : Fin 15) i) (added (12 : Fin 15) i) := by
  fin_cases i <;> decide

private theorem accepted_row_013 (i : Fin 4) :
    if special (13 : Fin 15) i then SeparatedAccepted (state (13 : Fin 15)) i (words (13 : Fin 15) i 0) (words (13 : Fin 15) i 1) (added (13 : Fin 15) i)
    else AcceptedRecord (state (13 : Fin 15)) i (words (13 : Fin 15) i) (added (13 : Fin 15) i) := by
  fin_cases i <;> decide

private theorem accepted_row_014 (i : Fin 4) :
    if special (14 : Fin 15) i then SeparatedAccepted (state (14 : Fin 15)) i (words (14 : Fin 15) i 0) (words (14 : Fin 15) i 1) (added (14 : Fin 15) i)
    else AcceptedRecord (state (14 : Fin 15)) i (words (14 : Fin 15) i) (added (14 : Fin 15) i) := by
  fin_cases i <;> decide

theorem accepted (o : Fin 15) (i : Fin 4) :
    if special o i then SeparatedAccepted (state o) i (words o i 0) (words o i 1) (added o i)
    else AcceptedRecord (state o) i (words o i) (added o i) := by
  fin_cases o
  · exact accepted_row_000 i
  · exact accepted_row_001 i
  · exact accepted_row_002 i
  · exact accepted_row_003 i
  · exact accepted_row_004 i
  · exact accepted_row_005 i
  · exact accepted_row_006 i
  · exact accepted_row_007 i
  · exact accepted_row_008 i
  · exact accepted_row_009 i
  · exact accepted_row_010 i
  · exact accepted_row_011 i
  · exact accepted_row_012 i
  · exact accepted_row_013 i
  · exact accepted_row_014 i


end Gallai.Certificate.SizeTwo.Rich.Catalogue.Block03
