/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.SizeTwoCatalogueKinds
import Gallai.Certificates.SizeTwoUniverse

/-! # Size-two ordinary orbit 223

Generated by scripts/import_size_two_catalogue.py from SHA256
fd5147fd306d683ad48417072994ce74056cad840b5d22648c0687d132a20da6.
Literal witnesses only. Lean checks basic acceptance; exception tags carry
no proof. Arbitrary labelled-state coverage remains a separate obligation.
-/

namespace Gallai.Certificate.SizeTwo.Catalogue.Orbit223
open Star.Vertex

/-- Original incidence rows. -/
def state : State := ![15,3,15,12,12]

/-- Non-basic kinds retain explicit outstanding obligations. -/
def kind : Fin 13 → RecordKind :=
  ![.forcedEndpoints,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic]

/-- Oriented basic words; exception slots contain no ordinary witness. -/
def words : Fin 13 → Fin 4 → List Star.Vertex :=
  ![![[],
    [],
    [],
    []],
    ![[p, a, q],
    [r, x, b],
    [s, x, a, b],
    []],
    ![[p, a, q],
    [r, x, a],
    [s, b, x, c],
    []],
    ![[p, x, q],
    [],
    [s, b, x, c],
    []],
    ![[p, a, q],
    [r, x, a],
    [s, b, x, c],
    []],
    ![[p, a],
    [q, a],
    [r, x, c],
    [s, b, x, d, c]],
    ![[p, a],
    [q, a],
    [r, x, b],
    [s, x, a, b]],
    ![[p, a],
    [q, a],
    [r, x, c],
    [s, b, x, d, c]],
    ![[p, a],
    [q, a],
    [r, x, b],
    [s, x, a, b]],
    ![[p, a],
    [q, a],
    [r, x, a],
    [s, b, x, c]],
    ![[p, a],
    [q, a],
    [r, x, a],
    [s, b, x, c]],
    ![[p, a],
    [q, x, a],
    [],
    [s, b, x, c]],
    ![[p, a],
    [q, a],
    [r, x, a],
    [s, b, x, c]]]

/-- Extra paths for basic records only. -/
def added : Fin 13 → List (List Star.Vertex) :=
  ![[],
    [[p, b, q, x, c, r, d, s], [p, x, d, c, s, b, r]],
    [[a, b, p, x, d, r, c, s], [c, d, s, x, q, b, r]],
    [[c, d, s, x, r, b, a, p], [p, b, q, a, x, d, r, c, s]],
    [[a, b, p, x, d, r, c, s], [c, d, s, x, q, b, r]],
    [[a, b, p, x, s, c, r], [a, x, q, b, r, d, s]],
    [[p, b, q, x, c, r, d, s], [p, x, d, c, s, b, r]],
    [[a, b, p, x, s, c, r], [a, x, q, b, r, d, s]],
    [[p, b, q, x, c, r, d, s], [p, x, d, c, s, b, r]],
    [[a, b, p, x, d, r, c, s], [c, d, s, x, q, b, r]],
    [[a, b, p, x, d, r, c, s], [c, d, s, x, q, b, r]],
    [[a, b, p, x, d, r, c, s], [a, q, b, r, x, s, d, c]],
    [[a, b, p, x, d, r, c, s], [c, d, s, x, q, b, r]]]

/-- Representative parity is checked independently of the importer. -/
theorem state_pair : PairState state := by decide

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every basic record satisfies the actual ordinary reconstruction contract. -/
theorem basic_accepted (i : Fin 13) (h : kind i = .basic) :
    OrdinaryAccepted state i (words i) (added i) := by
  revert i
  decide

end Gallai.Certificate.SizeTwo.Catalogue.Orbit223
