/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.SizeTwoCatalogueKinds
import Gallai.Certificates.SizeTwoUniverse

/-! # Size-two ordinary orbit 224

Generated by scripts/import_size_two_catalogue.py from SHA256
fd5147fd306d683ad48417072994ce74056cad840b5d22648c0687d132a20da6.
Literal witnesses only. Lean checks basic acceptance; exception tags carry
no proof. Arbitrary labelled-state coverage remains a separate obligation.
-/

namespace Gallai.Certificate.SizeTwo.Catalogue.Orbit224
open Star.Vertex

/-- Original incidence rows. -/
def state : State := ![15,3,15,15,15]

/-- Non-basic kinds retain explicit outstanding obligations. -/
def kind : Fin 13 → RecordKind :=
  ![.forcedEndpoints,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic]

/-- Oriented basic words; exception slots contain no ordinary witness. -/
def words : Fin 13 → Fin 4 → List Star.Vertex :=
  ![![[],
    [],
    [],
    []],
    ![[p, a, q],
    [r, x, c],
    [s, b, x, d, c],
    []],
    ![[p, a, q],
    [r, x, c],
    [s, b, x, d, c],
    []],
    ![[p, b, x, q],
    [],
    [s, c, d, x, a, b],
    []],
    ![[p, a, q],
    [r, x, c],
    [s, b, x, d, c],
    []],
    ![[p, a],
    [q, a],
    [r, x, c],
    [s, b, x, d, c]],
    ![[p, a],
    [q, a],
    [r, x, c],
    [s, b, x, d, c]],
    ![[p, a],
    [q, a],
    [r, x, c],
    [s, b, x, d, c]],
    ![[p, a],
    [q, a],
    [r, x, c],
    [s, b, x, d, c]],
    ![[p, a],
    [q, a],
    [r, x, c],
    [s, b, x, d, c]],
    ![[p, a],
    [q, a],
    [r, x, c],
    [s, b, x, d, c]],
    ![[p, a],
    [q, x, b],
    [r, b],
    [s, c, d, x, a]],
    ![[p, a],
    [q, a],
    [r, x, c],
    [s, b, x, d, c]]]

/-- Extra paths for basic records only. -/
def added : Fin 13 → List (List Star.Vertex) :=
  ![[],
    [[a, b, p, c, q, x, s, d, r], [a, x, p, d, q, b, r, c, s]],
    [[a, b, p, c, q, x, s, d, r], [a, x, p, d, q, b, r, c, s]],
    [[a, p, c, q, d, r, x, s, b], [a, q, b, r, c, x, p, d, s]],
    [[a, b, p, c, q, x, s, d, r], [a, x, p, d, q, b, r, c, s]],
    [[a, b, p, c, q, x, s, d, r], [a, x, p, d, q, b, r, c, s]],
    [[a, b, p, c, q, x, s, d, r], [a, x, p, d, q, b, r, c, s]],
    [[a, b, p, c, q, x, s, d, r], [a, x, p, d, q, b, r, c, s]],
    [[a, b, p, c, q, x, s, d, r], [a, x, p, d, q, b, r, c, s]],
    [[a, b, p, c, q, x, s, d, r], [a, x, p, d, q, b, r, c, s]],
    [[a, b, p, c, q, x, s, d, r], [a, x, p, d, q, b, r, c, s]],
    [[a, b, p, c, q, d, r, x, s], [a, q, b, s, d, p, x, c, r]],
    [[a, b, p, c, q, x, s, d, r], [a, x, p, d, q, b, r, c, s]]]

/-- Representative parity is checked independently of the importer. -/
theorem state_pair : PairState state := by decide

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every basic record satisfies the actual ordinary reconstruction contract. -/
theorem basic_accepted (i : Fin 13) (h : kind i = .basic) :
    OrdinaryAccepted state i (words i) (added i) := by
  revert i
  decide

end Gallai.Certificate.SizeTwo.Catalogue.Orbit224
