/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.SizeTwoCatalogueKinds
import Gallai.Certificates.SizeTwoUniverse

/-! # Size-two ordinary orbit 201

Generated by scripts/import_size_two_catalogue.py from SHA256
fd5147fd306d683ad48417072994ce74056cad840b5d22648c0687d132a20da6.
Literal witnesses only. Lean checks basic acceptance; exception tags carry
no proof. Arbitrary labelled-state coverage remains a separate obligation.
-/

namespace Gallai.Certificate.SizeTwo.Catalogue.Orbit201
open Star.Vertex

/-- Original incidence rows. -/
def state : State := ![15,0,0,5,9]

/-- Non-basic kinds retain explicit outstanding obligations. -/
def kind : Fin 13 → RecordKind :=
  ![.forcedEndpoints,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic]

/-- Oriented basic words; exception slots contain no ordinary witness. -/
def words : Fin 13 → Fin 4 → List Star.Vertex :=
  ![![[],
    [],
    [],
    []],
    ![[p, x, q],
    [],
    [s, x, a],
    []],
    ![[p, x, q],
    [r, x, a],
    [],
    []],
    ![[p, x, q],
    [],
    [s, x, a],
    []],
    ![[p, x, q],
    [],
    [s, x, a],
    []],
    ![[p, c],
    [q, x, a],
    [r, x, d],
    []],
    ![[p, c],
    [q, x],
    [r, x],
    [s, x, a]],
    ![[p, c],
    [q, x, a],
    [],
    [s, x, d]],
    ![[p, c],
    [q, x, a],
    [],
    [s, x, c]],
    ![[p, c],
    [q, x],
    [r, x],
    [s, x, a]],
    ![[p, c],
    [q, x, a],
    [r, x, c],
    []],
    ![[p, c],
    [q, x, a],
    [],
    [s, x, c]],
    ![[p, c],
    [q, x],
    [r, x],
    [s, x, a]]]

/-- Extra paths for basic records only. -/
def added : Fin 13 → List (List Star.Vertex) :=
  ![[],
    [[a, b, x, c, d, p], [p, c, r, x, d, s]],
    [[a, b, x, c, d, s], [r, c, p, d, x, s]],
    [[a, b, x, c, d, p], [p, c, r, x, d, s]],
    [[a, b, x, c, d, p], [p, c, r, x, d, s]],
    [[a, b, x, p, d, c], [d, s, x, c, r]],
    [[a, b, x, d, c], [r, c, x, p, d, s]],
    [[a, b, x, c, d], [c, r, x, p, d, s]],
    [[a, b, x, d, c], [c, r, x, p, d, s]],
    [[a, b, x, d, c], [r, c, x, p, d, s]],
    [[a, b, x, d, p], [p, x, s, d, c, r]],
    [[a, b, x, d, c], [c, r, x, p, d, s]],
    [[a, b, x, d, c], [r, c, x, p, d, s]]]

/-- Representative parity is checked independently of the importer. -/
theorem state_pair : PairState state := by decide

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every basic record satisfies the actual ordinary reconstruction contract. -/
theorem basic_accepted (i : Fin 13) (h : kind i = .basic) :
    OrdinaryAccepted state i (words i) (added i) := by
  revert i
  decide

end Gallai.Certificate.SizeTwo.Catalogue.Orbit201
