/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.SizeTwoCatalogueKinds
import Gallai.Certificates.SizeTwoUniverse

/-! # Size-two ordinary orbit 065

Generated by scripts/import_size_two_catalogue.py from SHA256
fd5147fd306d683ad48417072994ce74056cad840b5d22648c0687d132a20da6.
Literal witnesses only. Lean checks basic acceptance; exception tags carry
no proof. Arbitrary labelled-state coverage remains a separate obligation.
-/

namespace Gallai.Certificate.SizeTwo.Catalogue.Orbit065
open Star.Vertex

/-- Original incidence rows. -/
def state : State := ![3,5,5,6,6]

/-- Non-basic kinds retain explicit outstanding obligations. -/
def kind : Fin 13 → RecordKind :=
  ![.basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic]

/-- Oriented basic words; exception slots contain no ordinary witness. -/
def words : Fin 13 → Fin 4 → List Star.Vertex :=
  ![![[p, x, q],
    [],
    [],
    []],
    ![[p, x, q],
    [],
    [],
    []],
    ![[p, x, q],
    [],
    [],
    []],
    ![[p, x, q],
    [],
    [],
    []],
    ![[p, x, q],
    [],
    [],
    []],
    ![[p, a],
    [q, c],
    [r, b, x, c],
    []],
    ![[p, a],
    [q, c],
    [r, b, x, c],
    []],
    ![[p, a],
    [q, c],
    [r, a, x, b],
    []],
    ![[p, a],
    [q, c],
    [r, a, x, b],
    []],
    ![[p, a],
    [q, c],
    [r, a, x, b],
    []],
    ![[p, a],
    [q, c],
    [r, a, x, b],
    []],
    ![[p, a],
    [q, c],
    [r, a, x, b],
    []],
    ![[p, a],
    [q, c],
    [r, a, x, b],
    []]]

/-- Extra paths for basic records only. -/
def added : Fin 13 → List (List Star.Vertex) :=
  ![[[p, a, b, r, c, x, d, q], [p, b, x, a, r, d, c, q]],
    [[p, a, b, r, c, x, d, q], [p, b, x, a, r, d, c, q]],
    [[p, a, b, r, c, x, d, q], [p, b, x, a, r, d, c, q]],
    [[p, a, b, r, c, x, d, q], [p, b, x, a, r, d, c, q]],
    [[p, a, b, r, c, x, d, q], [p, b, x, a, r, d, c, q]],
    [[a, b, p, x, d, r, c], [c, d, q, x, a, r]],
    [[a, b, p, x, d, r, c], [c, d, q, x, a, r]],
    [[a, b, p, x, d, c, r], [b, r, d, q, x, c]],
    [[a, b, p, x, d, c, r], [b, r, d, q, x, c]],
    [[a, b, p, x, d, c, r], [b, r, d, q, x, c]],
    [[a, b, p, x, d, c, r], [b, r, d, q, x, c]],
    [[a, b, p, x, d, c, r], [b, r, d, q, x, c]],
    [[a, b, p, x, d, c, r], [b, r, d, q, x, c]]]

/-- Representative parity is checked independently of the importer. -/
theorem state_pair : PairState state := by decide

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every basic record satisfies the actual ordinary reconstruction contract. -/
theorem basic_accepted (i : Fin 13) (h : kind i = .basic) :
    OrdinaryAccepted state i (words i) (added i) := by
  revert i
  decide

end Gallai.Certificate.SizeTwo.Catalogue.Orbit065
