/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.SizeTwoCatalogueKinds
import Gallai.Certificates.SizeTwoUniverse

/-! # Size-two ordinary orbit 190

Generated by scripts/import_size_two_catalogue.py from SHA256
fd5147fd306d683ad48417072994ce74056cad840b5d22648c0687d132a20da6.
Literal witnesses only. Lean checks basic acceptance; exception tags carry
no proof. Arbitrary labelled-state coverage remains a separate obligation.
-/

namespace Gallai.Certificate.SizeTwo.Catalogue.Orbit190
open Star.Vertex

/-- Original incidence rows. -/
def state : State := ![12,5,5,5,10]

/-- Non-basic kinds retain explicit outstanding obligations. -/
def kind : Fin 13 → RecordKind :=
  ![.basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic]

/-- Oriented basic words; exception slots contain no ordinary witness. -/
def words : Fin 13 → Fin 4 → List Star.Vertex :=
  ![![[p, c, d, q],
    [],
    [s, x, a],
    []],
    ![[p, c, d, q],
    [],
    [s, x, a],
    []],
    ![[p, c, d, q],
    [],
    [s, x, a],
    []],
    ![[p, c, d, q],
    [],
    [s, x, a],
    []],
    ![[p, c, d, q],
    [],
    [s, x, a],
    []],
    ![[p, a],
    [q, d],
    [],
    [s, x, a]],
    ![[p, a],
    [q, d],
    [],
    [s, x, a]],
    ![[p, a],
    [q, d],
    [],
    [s, x, b]],
    ![[p, a],
    [q, d],
    [],
    [s, x, a]],
    ![[p, a],
    [q, d],
    [],
    [s, x, b]],
    ![[p, a],
    [q, d],
    [],
    [s, x, a]],
    ![[p, a],
    [q, d],
    [],
    [s, x, a]],
    ![[p, a],
    [q, d],
    [],
    [s, x, a]]]

/-- Extra paths for basic records only. -/
def added : Fin 13 → List (List Star.Vertex) :=
  ![[[a, b, r, x, c], [c, r, a, p, b, x, d, s]],
    [[a, b, r, x, c], [c, r, a, p, b, x, d, s]],
    [[a, b, r, x, c], [c, r, a, p, b, x, d, s]],
    [[a, b, r, x, c], [c, r, a, p, b, x, d, s]],
    [[a, b, r, x, c], [c, r, a, p, b, x, d, s]],
    [[a, b, p, c, r, x, d], [a, r, b, x, c, d, s]],
    [[a, b, p, c, r, x, d], [a, r, b, x, c, d, s]],
    [[a, b, p, c, r, x, d], [b, r, a, x, c, d, s]],
    [[a, b, p, c, r, x, d], [a, r, b, x, c, d, s]],
    [[a, b, p, c, r, x, d], [b, r, a, x, c, d, s]],
    [[a, b, p, c, r, x, d], [a, r, b, x, c, d, s]],
    [[a, b, p, c, r, x, d], [a, r, b, x, c, d, s]],
    [[a, b, p, c, r, x, d], [a, r, b, x, c, d, s]]]

/-- Representative parity is checked independently of the importer. -/
theorem state_pair : PairState state := by decide

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every basic record satisfies the actual ordinary reconstruction contract. -/
theorem basic_accepted (i : Fin 13) (h : kind i = .basic) :
    OrdinaryAccepted state i (words i) (added i) := by
  revert i
  decide

end Gallai.Certificate.SizeTwo.Catalogue.Orbit190
