/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.SizeTwoCatalogueKinds
import Gallai.Certificates.SizeTwoUniverse

/-! # Size-two ordinary orbit 206

Generated by scripts/import_size_two_catalogue.py from SHA256
fd5147fd306d683ad48417072994ce74056cad840b5d22648c0687d132a20da6.
Literal witnesses only. Lean checks basic acceptance; exception tags carry
no proof. Arbitrary labelled-state coverage remains a separate obligation.
-/

namespace Gallai.Certificate.SizeTwo.Catalogue.Orbit206
open Star.Vertex

/-- Original incidence rows. -/
def state : State := ![15,0,5,3,10]

/-- Non-basic kinds retain explicit outstanding obligations. -/
def kind : Fin 13 → RecordKind :=
  ![.forcedEndpoints,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic]

/-- Oriented basic words; exception slots contain no ordinary witness. -/
def words : Fin 13 → Fin 4 → List Star.Vertex :=
  ![![[],
    [],
    [],
    []],
    ![[p, c, q],
    [r, x, a],
    [s, x, c],
    []],
    ![[p, c, q],
    [r, x, a],
    [s, x, d],
    []],
    ![[p, x, q],
    [],
    [s, x, a],
    []],
    ![[p, c, q],
    [r, x, a],
    [s, x, c],
    []],
    ![[p, b],
    [q, c],
    [r, x, c],
    [s, x, b]],
    ![[p, b],
    [q, c],
    [r, x, c],
    [s, x, b]],
    ![[p, b],
    [q, c],
    [r, x, b],
    [s, x, c]],
    ![[p, b],
    [q, c],
    [r, x, b],
    [s, x, c]],
    ![[p, b],
    [q, c],
    [r, x, b],
    [s, x, c]],
    ![[p, b],
    [q, c],
    [r, x, b],
    [s, x, d]],
    ![[p, b],
    [q, x, a],
    [],
    [s, x, b]],
    ![[p, b],
    [q, c],
    [r, x, b],
    [s, x, c]]]

/-- Extra paths for basic records only. -/
def added : Fin 13 → List (List Star.Vertex) :=
  ![[],
    [[a, b, p, x, d, c], [r, b, x, q, d, s]],
    [[a, b, p, x, c, d], [r, b, x, q, d, s]],
    [[a, b, p, c, d, x, r], [r, b, x, c, q, d, s]],
    [[a, b, p, x, d, c], [r, b, x, q, d, s]],
    [[c, d, q, x, a, b, r], [c, p, x, d, s]],
    [[c, d, q, x, a, b, r], [c, p, x, d, s]],
    [[c, d, q, x, a, b, r], [c, p, x, d, s]],
    [[c, d, q, x, a, b, r], [c, p, x, d, s]],
    [[c, d, q, x, a, b, r], [c, p, x, d, s]],
    [[d, c, p, x, a, b, r], [c, x, q, d, s]],
    [[a, b, r, x, c, d, q], [q, c, p, x, d, s]],
    [[c, d, q, x, a, b, r], [c, p, x, d, s]]]

/-- Representative parity is checked independently of the importer. -/
theorem state_pair : PairState state := by decide

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every basic record satisfies the actual ordinary reconstruction contract. -/
theorem basic_accepted (i : Fin 13) (h : kind i = .basic) :
    OrdinaryAccepted state i (words i) (added i) := by
  revert i
  decide

end Gallai.Certificate.SizeTwo.Catalogue.Orbit206
