/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.SizeTwoCatalogueKinds
import Gallai.Certificates.SizeTwoUniverse

/-! # Size-two ordinary orbit 163

Generated by scripts/import_size_two_catalogue.py from SHA256
fd5147fd306d683ad48417072994ce74056cad840b5d22648c0687d132a20da6.
Literal witnesses only. Lean checks basic acceptance; exception tags carry
no proof. Arbitrary labelled-state coverage remains a separate obligation.
-/

namespace Gallai.Certificate.SizeTwo.Catalogue.Orbit163
open Star.Vertex

/-- Original incidence rows. -/
def state : State := ![5,10,15,12,15]

/-- Non-basic kinds retain explicit outstanding obligations. -/
def kind : Fin 13 → RecordKind :=
  ![.basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic]

/-- Oriented basic words; exception slots contain no ordinary witness. -/
def words : Fin 13 → Fin 4 → List Star.Vertex :=
  ![![[p, b, q],
    [],
    [s, d, x, a],
    []],
    ![[p, b, q],
    [],
    [s, d, x, a],
    []],
    ![[p, b, q],
    [],
    [s, d, x, a],
    []],
    ![[p, b, q],
    [],
    [s, d, x, a],
    []],
    ![[p, b, q],
    [],
    [s, d, x, a],
    []],
    ![[p, b],
    [q, a],
    [],
    [s, d, x, b]],
    ![[p, b],
    [q, a],
    [],
    [s, d, x, b]],
    ![[p, b],
    [q, a],
    [r, b],
    [s, d, x, a]],
    ![[p, b],
    [q, a],
    [],
    [s, d, x, b]],
    ![[p, b],
    [q, a],
    [r, b],
    [s, d, x, a]],
    ![[p, b],
    [q, a],
    [],
    [s, d, x, b]],
    ![[p, b],
    [q, a],
    [],
    [s, d, x, b]],
    ![[p, b],
    [q, a],
    [],
    [s, d, x, b]]]

/-- Extra paths for basic records only. -/
def added : Fin 13 → List (List Star.Vertex) :=
  ![[[a, b, s, c, x, r, d, p], [p, x, b, r, c, d, q, a, s]],
    [[a, b, s, c, x, r, d, p], [p, x, b, r, c, d, q, a, s]],
    [[a, b, s, c, x, r, d, p], [p, x, b, r, c, d, q, a, s]],
    [[a, b, s, c, x, r, d, p], [p, x, b, r, c, d, q, a, s]],
    [[a, b, s, c, x, r, d, p], [p, x, b, r, c, d, q, a, s]],
    [[a, b, s, c, d, r, x, p], [p, d, q, b, r, c, x, a, s]],
    [[a, b, s, c, d, r, x, p], [p, d, q, b, r, c, x, a, s]],
    [[a, b, q, d, p, x, r, c, s], [a, s, b, x, c, d, r]],
    [[a, b, s, c, d, r, x, p], [p, d, q, b, r, c, x, a, s]],
    [[a, b, q, d, p, x, r, c, s], [a, s, b, x, c, d, r]],
    [[a, b, s, c, d, r, x, p], [p, d, q, b, r, c, x, a, s]],
    [[a, b, s, c, d, r, x, p], [p, d, q, b, r, c, x, a, s]],
    [[a, b, s, c, d, r, x, p], [p, d, q, b, r, c, x, a, s]]]

/-- Representative parity is checked independently of the importer. -/
theorem state_pair : PairState state := by decide

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every basic record satisfies the actual ordinary reconstruction contract. -/
theorem basic_accepted (i : Fin 13) (h : kind i = .basic) :
    OrdinaryAccepted state i (words i) (added i) := by
  revert i
  decide

end Gallai.Certificate.SizeTwo.Catalogue.Orbit163
