/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.SizeTwoCatalogueKinds
import Gallai.Certificates.SizeTwoUniverse

/-! # Size-two ordinary orbit 083

Generated by scripts/import_size_two_catalogue.py from SHA256
fd5147fd306d683ad48417072994ce74056cad840b5d22648c0687d132a20da6.
Literal witnesses only. Lean checks basic acceptance; exception tags carry
no proof. Arbitrary labelled-state coverage remains a separate obligation.
-/

namespace Gallai.Certificate.SizeTwo.Catalogue.Orbit083
open Star.Vertex

/-- Original incidence rows. -/
def state : State := ![3,15,15,15,15]

/-- Non-basic kinds retain explicit outstanding obligations. -/
def kind : Fin 13 → RecordKind :=
  ![.forcedEndpoints,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic]

/-- Oriented basic words; exception slots contain no ordinary witness. -/
def words : Fin 13 → Fin 4 → List Star.Vertex :=
  ![![[],
    [],
    [],
    []],
    ![[p, a, q],
    [r, b],
    [s, c, d, x, a, b],
    []],
    ![[p, a, q],
    [r, a, b],
    [s, c, d, x, b],
    []],
    ![[p, a, b, q],
    [r, a],
    [s, c, d, x, b],
    []],
    ![[p, a, q],
    [r, a],
    [s, c, d, x, b, a],
    []],
    ![[p, a],
    [q, a],
    [r, c, x],
    [s, b, x, d, c]],
    ![[p, a],
    [q, a],
    [r, b],
    [s, c, d, x, a, b]],
    ![[p, a],
    [q, a],
    [r, c, x],
    [s, b, x, d, c]],
    ![[p, a],
    [q, a],
    [r, b],
    [s, c, d, x, a, b]],
    ![[p, a],
    [q, a],
    [r, a, b],
    [s, c, d, x, b]],
    ![[p, a],
    [q, a],
    [r, a, b],
    [s, c, d, x, b]],
    ![[p, a],
    [q, a, b],
    [r, a],
    [s, c, d, x, b]],
    ![[p, a],
    [q, a],
    [r, a],
    [s, c, d, x, b, a]]]

/-- Extra paths for basic records only. -/
def added : Fin 13 → List (List Star.Vertex) :=
  ![[],
    [[a, r, c, p, b, x, q, d, s], [a, s, b, q, c, x, p, d, r]],
    [[a, s, b, p, d, q, x, c, r], [a, x, p, c, q, b, r, d, s]],
    [[a, q, c, x, p, b, r, d, s], [b, s, a, x, q, d, p, c, r]],
    [[a, s, b, p, d, q, x, c, r], [a, x, p, c, q, b, r, d, s]],
    [[c, p, x, q, b, a, r, d, s], [r, b, p, d, q, c, s, a, x]],
    [[a, r, c, p, b, x, q, d, s], [a, s, b, q, c, x, p, d, r]],
    [[c, p, x, q, b, a, r, d, s], [r, b, p, d, q, c, s, a, x]],
    [[a, r, c, p, b, x, q, d, s], [a, s, b, q, c, x, p, d, r]],
    [[a, s, b, p, d, q, x, c, r], [a, x, p, c, q, b, r, d, s]],
    [[a, s, b, p, d, q, x, c, r], [a, x, p, c, q, b, r, d, s]],
    [[a, s, b, p, d, q, x, c, r], [a, x, p, c, q, b, r, d, s]],
    [[a, s, b, p, d, q, x, c, r], [a, x, p, c, q, b, r, d, s]]]

/-- Representative parity is checked independently of the importer. -/
theorem state_pair : PairState state := by decide

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every basic record satisfies the actual ordinary reconstruction contract. -/
theorem basic_accepted (i : Fin 13) (h : kind i = .basic) :
    OrdinaryAccepted state i (words i) (added i) := by
  revert i
  decide

end Gallai.Certificate.SizeTwo.Catalogue.Orbit083
