/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.SizeTwoCatalogueKinds
import Gallai.Certificates.SizeTwoUniverse

/-! # Size-two ordinary orbit 210

Generated by scripts/import_size_two_catalogue.py from SHA256
fd5147fd306d683ad48417072994ce74056cad840b5d22648c0687d132a20da6.
Literal witnesses only. Lean checks basic acceptance; exception tags carry
no proof. Arbitrary labelled-state coverage remains a separate obligation.
-/

namespace Gallai.Certificate.SizeTwo.Catalogue.Orbit210
open Star.Vertex

/-- Original incidence rows. -/
def state : State := ![15,0,12,5,5]

/-- Non-basic kinds retain explicit outstanding obligations. -/
def kind : Fin 13 → RecordKind :=
  ![.forcedEndpoints,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic]

/-- Oriented basic words; exception slots contain no ordinary witness. -/
def words : Fin 13 → Fin 4 → List Star.Vertex :=
  ![![[],
    [],
    [],
    []],
    ![[p, x, q],
    [],
    [s, x, a],
    []],
    ![[p, x, q],
    [r, x, a],
    [],
    []],
    ![[p, x, q],
    [],
    [s, x, a],
    []],
    ![[p, x, q],
    [],
    [s, x, a],
    []],
    ![[p, c],
    [q, x, a],
    [r, x, b],
    []],
    ![[p, c],
    [q, x],
    [r, x],
    [s, x, a]],
    ![[p, c],
    [q, x, a],
    [],
    [s, x, d]],
    ![[p, c],
    [q, x, a],
    [],
    [s, x, c]],
    ![[p, c],
    [q, x],
    [r, x],
    [s, x, a]],
    ![[p, c],
    [q, x, a],
    [r, x, b],
    []],
    ![[p, c],
    [q, x, a],
    [],
    [s, x, c]],
    ![[p, c],
    [q, x],
    [r, x],
    [s, x, a]]]

/-- Extra paths for basic records only. -/
def added : Fin 13 → List (List Star.Vertex) :=
  ![[],
    [[a, b, r, c, x, d, p], [p, c, d, r, x, b, s]],
    [[a, b, r, c, d, x, s], [r, d, p, c, x, b, s]],
    [[a, b, r, c, x, d, p], [p, c, d, r, x, b, s]],
    [[a, b, r, c, x, d, p], [p, c, d, r, x, b, s]],
    [[a, b, r, d, p, x, c], [b, s, x, d, c, r]],
    [[a, b, r, d, p, x, c], [r, c, d, x, b, s]],
    [[a, b, r, c, x, p, d], [c, d, r, x, b, s]],
    [[a, b, r, c, d, x, p], [p, d, r, x, b, s]],
    [[a, b, r, d, p, x, c], [r, c, d, x, b, s]],
    [[a, b, r, d, p, x, c], [b, s, x, d, c, r]],
    [[a, b, r, c, d, x, p], [p, d, r, x, b, s]],
    [[a, b, r, d, p, x, c], [r, c, d, x, b, s]]]

/-- Representative parity is checked independently of the importer. -/
theorem state_pair : PairState state := by decide

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every basic record satisfies the actual ordinary reconstruction contract. -/
theorem basic_accepted (i : Fin 13) (h : kind i = .basic) :
    OrdinaryAccepted state i (words i) (added i) := by
  revert i
  decide

end Gallai.Certificate.SizeTwo.Catalogue.Orbit210
