/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.SizeTwoCatalogueKinds
import Gallai.Certificates.SizeTwoUniverse

/-! # Size-two ordinary orbit 229

Generated by scripts/import_size_two_catalogue.py from SHA256
fd5147fd306d683ad48417072994ce74056cad840b5d22648c0687d132a20da6.
Literal witnesses only. Lean checks basic acceptance; exception tags carry
no proof. Arbitrary labelled-state coverage remains a separate obligation.
-/

namespace Gallai.Certificate.SizeTwo.Catalogue.Orbit229
open Star.Vertex

/-- Original incidence rows. -/
def state : State := ![15,5,9,15,15]

/-- Non-basic kinds retain explicit outstanding obligations. -/
def kind : Fin 13 → RecordKind :=
  ![.forcedEndpoints,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic,
    .basic]

/-- Oriented basic words; exception slots contain no ordinary witness. -/
def words : Fin 13 → Fin 4 → List Star.Vertex :=
  ![![[],
    [],
    [],
    []],
    ![[p, c, q],
    [r, x, a],
    [s, d, x, b],
    []],
    ![[p, c, q],
    [r, x, a],
    [s, d, x, b],
    []],
    ![[p, x, q],
    [],
    [s, c, d, x, a],
    []],
    ![[p, c, q],
    [r, x, a],
    [s, d, x, b],
    []],
    ![[p, a],
    [q, c],
    [r, x, c],
    [s, d, x, a]],
    ![[p, a],
    [q, c],
    [r, x, b],
    [s, d, x, c]],
    ![[p, a],
    [q, c],
    [r, x, a],
    [s, d, x, c]],
    ![[p, a],
    [q, c],
    [r, x, a],
    [s, d, x, c]],
    ![[p, a],
    [q, c],
    [r, x, a],
    [s, d, x, c]],
    ![[p, a],
    [q, c],
    [r, x, c],
    [s, d, x, a]],
    ![[p, a],
    [q, x, a],
    [],
    [s, c, d, x, b]],
    ![[p, a],
    [q, c],
    [r, x, a],
    [s, d, x, c]]]

/-- Extra paths for basic records only. -/
def added : Fin 13 → List (List Star.Vertex) :=
  ![[],
    [[a, b, p, d, r, c, x, s], [b, s, c, d, q, x, p, a, r]],
    [[a, b, p, d, r, c, x, s], [b, s, c, d, q, x, p, a, r]],
    [[a, b, p, d, s, x, r, c, q], [q, d, r, a, p, c, x, b, s]],
    [[a, b, p, d, r, c, x, s], [b, s, c, d, q, x, p, a, r]],
    [[a, b, p, c, s, x, q, d, r], [a, r, c, d, p, x, b, s]],
    [[a, b, p, c, r, d, q, x, s], [b, s, c, d, p, x, a, r]],
    [[a, b, p, c, s, x, q, d, r], [a, r, c, d, p, x, b, s]],
    [[a, b, p, c, s, x, q, d, r], [a, r, c, d, p, x, b, s]],
    [[a, b, p, c, s, x, q, d, r], [a, r, c, d, p, x, b, s]],
    [[a, b, p, c, s, x, q, d, r], [a, r, c, d, p, x, b, s]],
    [[a, b, p, c, q, d, r, x, s], [a, r, c, x, p, d, s, b]],
    [[a, b, p, c, s, x, q, d, r], [a, r, c, d, p, x, b, s]]]

/-- Representative parity is checked independently of the importer. -/
theorem state_pair : PairState state := by decide

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every basic record satisfies the actual ordinary reconstruction contract. -/
theorem basic_accepted (i : Fin 13) (h : kind i = .basic) :
    OrdinaryAccepted state i (words i) (added i) := by
  revert i
  decide

end Gallai.Certificate.SizeTwo.Catalogue.Orbit229
