/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.SizeTwoForced
import Gallai.Certificates.SizeTwoCatalogueRows

/-! # Size-two forced-endpoint literal witnesses

Generated by scripts/import_size_two_catalogue.py from SHA256
fd5147fd306d683ad48417072994ce74056cad840b5d22648c0687d132a20da6.
Literal witnesses only. Lean checks basic acceptance; exception tags carry
no proof. Arbitrary labelled-state coverage remains a separate obligation.
-/

namespace Gallai.Certificate.SizeTwo.Forced.Catalogue
open Star.Vertex
set_option maxRecDepth 100000
set_option maxHeartbeats 0

/-- Literal orbit from the pinned forced records. -/
def orbit : Fin 34 → Fin 234 :=
  ![83,
    200,
    201,
    202,
    203,
    204,
    205,
    206,
    207,
    208,
    209,
    210,
    212,
    213,
    214,
    215,
    216,
    217,
    218,
    219,
    220,
    221,
    222,
    223,
    224,
    225,
    226,
    227,
    228,
    229,
    230,
    231,
    232,
    233]

/-- Literal state from the pinned forced records. -/
def state : Fin 34 → State :=
  ![![3,15,15,15,15],
    ![15,0,0,3,15],
    ![15,0,0,5,9],
    ![15,0,3,0,15],
    ![15,0,3,3,12],
    ![15,0,3,5,10],
    ![15,0,5,0,9],
    ![15,0,5,3,10],
    ![15,0,5,5,12],
    ![15,0,5,6,15],
    ![15,0,12,3,3],
    ![15,0,12,5,5],
    ![15,0,12,15,15],
    ![15,0,15,5,6],
    ![15,0,15,12,15],
    ![15,3,3,3,15],
    ![15,3,3,5,9],
    ![15,3,5,3,9],
    ![15,3,5,5,15],
    ![15,3,5,6,12],
    ![15,3,12,5,6],
    ![15,3,12,12,15],
    ![15,3,15,5,5],
    ![15,3,15,12,12],
    ![15,3,15,15,15],
    ![15,5,5,5,9],
    ![15,5,5,6,10],
    ![15,5,6,5,10],
    ![15,5,9,12,12],
    ![15,5,9,15,15],
    ![15,5,10,12,15],
    ![15,5,12,9,12],
    ![15,5,12,10,15],
    ![15,5,15,9,15]]

/-- Literal extraIndex from the pinned forced records. -/
def extraIndex : Fin 34 → Fin 2 :=
  ![1,
    1,
    0,
    1,
    1,
    1,
    0,
    1,
    0,
    1,
    1,
    0,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    0,
    1,
    1,
    0,
    1,
    1,
    0,
    1,
    1]

/-- Literal connector from the pinned forced records. -/
def connector : Fin 34 → List Star.Vertex :=
  ![[p, a, q],
    [p, c, q],
    [p, x, q],
    [p, b, q],
    [p, b, q],
    [p, b, q],
    [p, x, q],
    [p, c, q],
    [p, x, q],
    [p, d, q],
    [p, c, q],
    [p, x, q],
    [p, c, q],
    [p, b, q],
    [p, b, q],
    [p, a, q],
    [p, a, q],
    [p, a, q],
    [p, a, q],
    [p, a, q],
    [p, a, q],
    [p, a, q],
    [p, a, q],
    [p, a, q],
    [p, a, q],
    [p, x, q],
    [p, x, q],
    [p, x, q],
    [p, x, q],
    [p, c, q],
    [p, d, q],
    [p, x, q],
    [p, d, q],
    [p, b, q]]

/-- Literal extra from the pinned forced records. -/
def extra : Fin 34 → List Star.Vertex :=
  ![[q, b, a],
    [q, x, a],
    [p, c, x, a],
    [q, x, a],
    [q, x, a],
    [q, x, a],
    [p, b, x, a],
    [q, x, a],
    [p, b, x, a],
    [q, x, a],
    [q, x, a],
    [p, c, x, a],
    [q, x, a],
    [q, x, a],
    [q, x, a],
    [q, x, a],
    [q, x, a],
    [q, x, a],
    [q, x, a],
    [q, x, a],
    [q, x, a],
    [q, x, a],
    [q, x, a],
    [q, x, a],
    [q, x, c],
    [p, a, x, b],
    [q, c, x, a],
    [q, b, x, a],
    [p, a, x, b],
    [q, x, a],
    [q, x, a],
    [p, a, x, b],
    [q, x, a],
    [q, x, a]]

/-- Literal tail from the pinned forced records. -/
def tail : Fin 34 → List Star.Vertex :=
  ![[s, c, d, x, b],
    [s, d, x, b, a],
    [],
    [s, d, x, c],
    [s, x, c],
    [s, x, c],
    [],
    [s, x, b],
    [],
    [s, x, b],
    [s, x, d],
    [],
    [s, d, x, b],
    [s, x, c],
    [s, d, x, c],
    [s, d, x, b],
    [s, x, c],
    [s, x, b],
    [s, d, x, b],
    [s, x, b],
    [s, x, c],
    [s, d, x, b],
    [s, b, x, c],
    [s, b, x, c],
    [s, b, x, d, c],
    [],
    [],
    [],
    [s, c],
    [s, d, x, b],
    [s, x, b],
    [],
    [s, x, b],
    [s, d, x, c]]

/-- Literal added from the pinned forced records. -/
def added : Fin 34 → List (List Star.Vertex) :=
  ![[[a, r, b, p, c, x, q, d, s], [b, s, a, x, p, d, r, c, q]],
    [[c, d, p, x, s], [c, x, r, d, q]],
    [[a, b, x, d, c], [c, r, x, s, d, p]],
    [[a, b, x, p, d, c], [q, d, r, x, s]],
    [[a, b, x, d, c], [q, c, p, x, r, d, s]],
    [[a, b, x, p, c, d, q], [c, r, x, d, s]],
    [[a, b, r, x, c, d, s], [p, d, x, s]],
    [[a, b, p, x, c, d, q], [b, r, x, d, s]],
    [[a, b, r, c, d, x, s], [p, c, x, r, d, s]],
    [[a, b, p, x, c, r, d, s], [b, r, x, d, c, q]],
    [[a, b, r, x, c, d], [q, d, p, x, b, s]],
    [[a, b, r, c, d, x, s], [p, d, r, x, b, s]],
    [[a, b, r, c, d, p, x, s], [b, s, c, x, r, d, q]],
    [[a, b, r, c, p, x, d, q], [c, d, r, x, b, s]],
    [[a, b, r, c, d, p, x, s], [c, s, b, x, r, d, q]],
    [[a, b, p, c, x, r, d, q], [b, q, c, d, p, x, s]],
    [[a, b, p, c, r, x, d, s], [c, d, p, x, b, q]],
    [[a, b, p, c, x, d, s], [b, r, x, p, d, c, q]],
    [[a, b, p, c, d, r, x, s], [b, r, c, x, p, d, q]],
    [[a, b, p, x, c, r, d, s], [b, r, x, d, c, q]],
    [[a, b, r, c, p, x, d, q], [c, d, r, x, b, s]],
    [[a, b, r, c, d, p, x, s], [b, s, c, x, r, d, q]],
    [[a, b, p, c, r, d, x, s], [c, d, p, x, r, b, q]],
    [[a, b, p, x, d, r, c, s], [c, d, s, x, r, b, q]],
    [[a, b, p, c, q, d, r, x, s], [a, x, p, d, s, c, r, b, q]],
    [[a, b, r, c, x, d, p], [a, r, x, s, d, c, p, b]],
    [[a, b, r, x, d, c], [c, r, a, p, b, x, s, d, q]],
    [[a, b, r, c, x, d, s], [q, d, c, p, a, r, x, s]],
    [[b, a, r, c, d, x, s], [c, x, r, d, s, b, p]],
    [[a, b, p, d, c, r, x, s], [b, s, c, x, p, a, r, d, q]],
    [[b, a, p, x, c, r, d, s], [a, r, x, d, c, s, b, q]],
    [[a, b, r, d, s, x, c, p], [a, r, x, d, c, s, b]],
    [[a, b, r, x, d, c, s], [b, s, d, r, a, p, x, c, q]],
    [[a, b, r, d, c, p, x, s], [c, s, b, x, r, a, p, d, q]]]

/-- Every literal forced record satisfies the one-extra-endpoint contract. -/
theorem accepted (i : Fin 34) : AcceptedRecord (state i) (extraIndex i)
    (connector i) (extra i) (tail i) (added i) := by
  fin_cases i <;> decide

/-- Each forced state agrees with its ordinary catalogue representative. -/
theorem state_eq_rows (i : Fin 34) :
    state i = SizeTwo.Catalogue.Rows.state (orbit i) := by
  fin_cases i <;> rfl

end Gallai.Certificate.SizeTwo.Forced.Catalogue
