/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.SizeTwoRichCatalogue
import Gallai.Certificates.SizeTwoCatalogueRows
import Gallai.Certificates.ZeroSyndromeUniverse

/-! # Coverage of every high-activity size-two representative

Generated by scripts/import_size_two_rich.py. Rich SHA256 943309a1cd4fafcbe0c4f70825b5fe92dd920134337011be917a0ada47d52bda;
ordinary SHA256 fd5147fd306d683ad48417072994ce74056cad840b5d22648c0687d132a20da6.
Each missing rich representative is excluded by the independently defined
HighBoundary predicate, not by a successful importer or a counted record set.
-/
namespace Gallai.Certificate.SizeTwo.Rich.Catalogue
set_option maxRecDepth 100000
set_option maxHeartbeats 0

/-- Every full-anchor high-activity representative has all four rich interfaces. -/
theorem high_representative_covered (o : Fin 234)
    (h : ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state o)) :
    ∃ b : Fin 12, ∃ k : Fin 15, state b k = SizeTwo.Catalogue.Rows.state o := by
  fin_cases o
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 0)) h)
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 1)) h)
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 2)) h)
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 3)) h)
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 4)) h)
  · exact ⟨0,0,rfl⟩
  · exact ⟨0,1,rfl⟩
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 7)) h)
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 8)) h)
  · exact ⟨0,2,rfl⟩
  · exact ⟨0,3,rfl⟩
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 11)) h)
  · exact ⟨0,4,rfl⟩
  · exact ⟨0,5,rfl⟩
  · exact ⟨0,6,rfl⟩
  · exact ⟨0,7,rfl⟩
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 16)) h)
  · exact ⟨0,8,rfl⟩
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 18)) h)
  · exact ⟨0,9,rfl⟩
  · exact ⟨0,10,rfl⟩
  · exact ⟨0,11,rfl⟩
  · exact ⟨0,12,rfl⟩
  · exact ⟨0,13,rfl⟩
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 24)) h)
  · exact ⟨0,14,rfl⟩
  · exact ⟨1,0,rfl⟩
  · exact ⟨1,1,rfl⟩
  · exact ⟨1,2,rfl⟩
  · exact ⟨1,3,rfl⟩
  · exact ⟨1,4,rfl⟩
  · exact ⟨1,5,rfl⟩
  · exact ⟨1,6,rfl⟩
  · exact ⟨1,7,rfl⟩
  · exact ⟨1,8,rfl⟩
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 35)) h)
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 36)) h)
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 37)) h)
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 38)) h)
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 39)) h)
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 40)) h)
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 41)) h)
  · exact ⟨1,9,rfl⟩
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 43)) h)
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 44)) h)
  · exact ⟨1,10,rfl⟩
  · exact ⟨1,11,rfl⟩
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 47)) h)
  · exact ⟨1,12,rfl⟩
  · exact ⟨1,13,rfl⟩
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 50)) h)
  · exact ⟨1,14,rfl⟩
  · exact ⟨2,0,rfl⟩
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 53)) h)
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 54)) h)
  · exact ⟨2,1,rfl⟩
  · exact ⟨2,2,rfl⟩
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 57)) h)
  · exact ⟨2,3,rfl⟩
  · exact ⟨2,4,rfl⟩
  · exact ⟨2,5,rfl⟩
  · exact ⟨2,6,rfl⟩
  · exact ⟨2,7,rfl⟩
  · exact ⟨2,8,rfl⟩
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 64)) h)
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 65)) h)
  · exact ⟨2,9,rfl⟩
  · exact ⟨2,10,rfl⟩
  · exact ⟨2,11,rfl⟩
  · exact ⟨2,12,rfl⟩
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 70)) h)
  · exact ⟨2,13,rfl⟩
  · exact ⟨2,14,rfl⟩
  · exact ⟨3,0,rfl⟩
  · exact ⟨3,1,rfl⟩
  · exact ⟨3,2,rfl⟩
  · exact ⟨3,3,rfl⟩
  · exact ⟨3,4,rfl⟩
  · exact ⟨3,5,rfl⟩
  · exact ⟨3,6,rfl⟩
  · exact ⟨3,7,rfl⟩
  · exact ⟨3,8,rfl⟩
  · exact ⟨3,9,rfl⟩
  · exact ⟨3,10,rfl⟩
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 84)) h)
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 85)) h)
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 86)) h)
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 87)) h)
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 88)) h)
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 89)) h)
  · exact ⟨3,11,rfl⟩
  · exact ⟨3,12,rfl⟩
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 92)) h)
  · exact ⟨3,13,rfl⟩
  · exact ⟨3,14,rfl⟩
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 95)) h)
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 96)) h)
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 97)) h)
  · exact ⟨4,0,rfl⟩
  · exact ⟨4,1,rfl⟩
  · exact ⟨4,2,rfl⟩
  · exact ⟨4,3,rfl⟩
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 102)) h)
  · exact ⟨4,4,rfl⟩
  · exact ⟨4,5,rfl⟩
  · exact ⟨4,6,rfl⟩
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 106)) h)
  · exact ⟨4,7,rfl⟩
  · exact ⟨4,8,rfl⟩
  · exact ⟨4,9,rfl⟩
  · exact ⟨4,10,rfl⟩
  · exact ⟨4,11,rfl⟩
  · exact ⟨4,12,rfl⟩
  · exact ⟨4,13,rfl⟩
  · exact ⟨4,14,rfl⟩
  · exact ⟨5,0,rfl⟩
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 116)) h)
  · exact ⟨5,1,rfl⟩
  · exact ⟨5,2,rfl⟩
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 119)) h)
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 120)) h)
  · exact ⟨5,3,rfl⟩
  · exact ⟨5,4,rfl⟩
  · exact ⟨5,5,rfl⟩
  · exact ⟨5,6,rfl⟩
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 125)) h)
  · exact ⟨5,7,rfl⟩
  · exact ⟨5,8,rfl⟩
  · exact ⟨5,9,rfl⟩
  · exact ⟨5,10,rfl⟩
  · exact ⟨5,11,rfl⟩
  · exact ⟨5,12,rfl⟩
  · exact ⟨5,13,rfl⟩
  · exact ⟨5,14,rfl⟩
  · exact ⟨6,0,rfl⟩
  · exact ⟨6,1,rfl⟩
  · exact ⟨6,2,rfl⟩
  · exact ⟨6,3,rfl⟩
  · exact ⟨6,4,rfl⟩
  · exact ⟨6,5,rfl⟩
  · exact ⟨6,6,rfl⟩
  · exact ⟨6,7,rfl⟩
  · exact ⟨6,8,rfl⟩
  · exact ⟨6,9,rfl⟩
  · exact ⟨6,10,rfl⟩
  · exact ⟨6,11,rfl⟩
  · exact ⟨6,12,rfl⟩
  · exact ⟨6,13,rfl⟩
  · exact ⟨6,14,rfl⟩
  · exact ⟨7,0,rfl⟩
  · exact ⟨7,1,rfl⟩
  · exact ⟨7,2,rfl⟩
  · exact ⟨7,3,rfl⟩
  · exact ⟨7,4,rfl⟩
  · exact ⟨7,5,rfl⟩
  · exact ⟨7,6,rfl⟩
  · exact ⟨7,7,rfl⟩
  · exact ⟨7,8,rfl⟩
  · exact ⟨7,9,rfl⟩
  · exact ⟨7,10,rfl⟩
  · exact ⟨7,11,rfl⟩
  · exact ⟨7,12,rfl⟩
  · exact ⟨7,13,rfl⟩
  · exact ⟨7,14,rfl⟩
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 164)) h)
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 165)) h)
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 166)) h)
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 167)) h)
  · exact ⟨8,0,rfl⟩
  · exact ⟨8,1,rfl⟩
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 170)) h)
  · exact ⟨8,2,rfl⟩
  · exact ⟨8,3,rfl⟩
  · exact ⟨8,4,rfl⟩
  · exact ⟨8,5,rfl⟩
  · exact ⟨8,6,rfl⟩
  · exact ⟨8,7,rfl⟩
  · exact ⟨8,8,rfl⟩
  · exact ⟨8,9,rfl⟩
  · exact ⟨8,10,rfl⟩
  · exact ⟨8,11,rfl⟩
  · exact ⟨8,12,rfl⟩
  · exact ⟨8,13,rfl⟩
  · exact ⟨8,14,rfl⟩
  · exact ⟨9,0,rfl⟩
  · exact ⟨9,1,rfl⟩
  · exact ⟨9,2,rfl⟩
  · exact ⟨9,3,rfl⟩
  · exact ⟨9,4,rfl⟩
  · exact ⟨9,5,rfl⟩
  · exact ⟨9,6,rfl⟩
  · exact ⟨9,7,rfl⟩
  · exact ⟨9,8,rfl⟩
  · exact ⟨9,9,rfl⟩
  · exact ⟨9,10,rfl⟩
  · exact ⟨9,11,rfl⟩
  · exact ⟨9,12,rfl⟩
  · exact ⟨9,13,rfl⟩
  · exact ⟨9,14,rfl⟩
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 199)) h)
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 200)) h)
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 201)) h)
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 202)) h)
  · exact ⟨10,0,rfl⟩
  · exact ⟨10,1,rfl⟩
  · exact False.elim ((by decide : ¬ ZeroSyndrome.HighBoundary (SizeTwo.Catalogue.Rows.state 205)) h)
  · exact ⟨10,2,rfl⟩
  · exact ⟨10,3,rfl⟩
  · exact ⟨10,4,rfl⟩
  · exact ⟨10,5,rfl⟩
  · exact ⟨10,6,rfl⟩
  · exact ⟨10,7,rfl⟩
  · exact ⟨10,8,rfl⟩
  · exact ⟨10,9,rfl⟩
  · exact ⟨10,10,rfl⟩
  · exact ⟨10,11,rfl⟩
  · exact ⟨10,12,rfl⟩
  · exact ⟨10,13,rfl⟩
  · exact ⟨10,14,rfl⟩
  · exact ⟨11,0,rfl⟩
  · exact ⟨11,1,rfl⟩
  · exact ⟨11,2,rfl⟩
  · exact ⟨11,3,rfl⟩
  · exact ⟨11,4,rfl⟩
  · exact ⟨11,5,rfl⟩
  · exact ⟨11,6,rfl⟩
  · exact ⟨11,7,rfl⟩
  · exact ⟨11,8,rfl⟩
  · exact ⟨11,9,rfl⟩
  · exact ⟨11,10,rfl⟩
  · exact ⟨11,11,rfl⟩
  · exact ⟨11,12,rfl⟩
  · exact ⟨11,13,rfl⟩
  · exact ⟨11,14,rfl⟩

end Gallai.Certificate.SizeTwo.Rich.Catalogue
