/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit000
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit001
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit002
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit003
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit004
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit005
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit006
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit007
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit008
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit009
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit010
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit011
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit012
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit013
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit014
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit015
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit016
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit017
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit018
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit019
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit020
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit021
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit022
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit023
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit024
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit025
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit026
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit027
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit028
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit029
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit030
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit031
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit032
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit033
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit034
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit035
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit036
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit037
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit038
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit039
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit040
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit041
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit042
import Gallai.Certificates.ZeroSyndromeCatalogue.Orbit043
import Mathlib.Tactic.FinCases

/-! # Accepted zero-syndrome representative records

Generated by scripts/import_zero_syndrome_catalogue.py from SHA256
32c2c172fa37de8b8de229fb2f531543e2e9274cfa5316796c582c6989ebdd59.
Literal data; ordinary Lean decision reduction checks acceptance.
Coverage of arbitrary labelled states is a separate obligation.
-/

namespace Gallai.Certificate.ZeroSyndrome.Catalogue

/-- Literal state selected by representative index. -/
def state : Fin 44 → CompletedStar.State :=
  ![Orbit000.state,
    Orbit001.state,
    Orbit002.state,
    Orbit003.state,
    Orbit004.state,
    Orbit005.state,
    Orbit006.state,
    Orbit007.state,
    Orbit008.state,
    Orbit009.state,
    Orbit010.state,
    Orbit011.state,
    Orbit012.state,
    Orbit013.state,
    Orbit014.state,
    Orbit015.state,
    Orbit016.state,
    Orbit017.state,
    Orbit018.state,
    Orbit019.state,
    Orbit020.state,
    Orbit021.state,
    Orbit022.state,
    Orbit023.state,
    Orbit024.state,
    Orbit025.state,
    Orbit026.state,
    Orbit027.state,
    Orbit028.state,
    Orbit029.state,
    Orbit030.state,
    Orbit031.state,
    Orbit032.state,
    Orbit033.state,
    Orbit034.state,
    Orbit035.state,
    Orbit036.state,
    Orbit037.state,
    Orbit038.state,
    Orbit039.state,
    Orbit040.state,
    Orbit041.state,
    Orbit042.state,
    Orbit043.state]

/-- Literal twoTails selected by representative index. -/
def twoTails : Fin 44 → Fin 51 → Tails :=
  ![Orbit000.twoTails,
    Orbit001.twoTails,
    Orbit002.twoTails,
    Orbit003.twoTails,
    Orbit004.twoTails,
    Orbit005.twoTails,
    Orbit006.twoTails,
    Orbit007.twoTails,
    Orbit008.twoTails,
    Orbit009.twoTails,
    Orbit010.twoTails,
    Orbit011.twoTails,
    Orbit012.twoTails,
    Orbit013.twoTails,
    Orbit014.twoTails,
    Orbit015.twoTails,
    Orbit016.twoTails,
    Orbit017.twoTails,
    Orbit018.twoTails,
    Orbit019.twoTails,
    Orbit020.twoTails,
    Orbit021.twoTails,
    Orbit022.twoTails,
    Orbit023.twoTails,
    Orbit024.twoTails,
    Orbit025.twoTails,
    Orbit026.twoTails,
    Orbit027.twoTails,
    Orbit028.twoTails,
    Orbit029.twoTails,
    Orbit030.twoTails,
    Orbit031.twoTails,
    Orbit032.twoTails,
    Orbit033.twoTails,
    Orbit034.twoTails,
    Orbit035.twoTails,
    Orbit036.twoTails,
    Orbit037.twoTails,
    Orbit038.twoTails,
    Orbit039.twoTails,
    Orbit040.twoTails,
    Orbit041.twoTails,
    Orbit042.twoTails,
    Orbit043.twoTails]

/-- Literal twoAdded selected by representative index. -/
def twoAdded : Fin 44 → Fin 51 → List (List Star.Vertex) :=
  ![Orbit000.twoAdded,
    Orbit001.twoAdded,
    Orbit002.twoAdded,
    Orbit003.twoAdded,
    Orbit004.twoAdded,
    Orbit005.twoAdded,
    Orbit006.twoAdded,
    Orbit007.twoAdded,
    Orbit008.twoAdded,
    Orbit009.twoAdded,
    Orbit010.twoAdded,
    Orbit011.twoAdded,
    Orbit012.twoAdded,
    Orbit013.twoAdded,
    Orbit014.twoAdded,
    Orbit015.twoAdded,
    Orbit016.twoAdded,
    Orbit017.twoAdded,
    Orbit018.twoAdded,
    Orbit019.twoAdded,
    Orbit020.twoAdded,
    Orbit021.twoAdded,
    Orbit022.twoAdded,
    Orbit023.twoAdded,
    Orbit024.twoAdded,
    Orbit025.twoAdded,
    Orbit026.twoAdded,
    Orbit027.twoAdded,
    Orbit028.twoAdded,
    Orbit029.twoAdded,
    Orbit030.twoAdded,
    Orbit031.twoAdded,
    Orbit032.twoAdded,
    Orbit033.twoAdded,
    Orbit034.twoAdded,
    Orbit035.twoAdded,
    Orbit036.twoAdded,
    Orbit037.twoAdded,
    Orbit038.twoAdded,
    Orbit039.twoAdded,
    Orbit040.twoAdded,
    Orbit041.twoAdded,
    Orbit042.twoAdded,
    Orbit043.twoAdded]

/-- Literal oneTails selected by representative index. -/
def oneTails : Fin 44 → Fin 7 → Tails :=
  ![Orbit000.oneTails,
    Orbit001.oneTails,
    Orbit002.oneTails,
    Orbit003.oneTails,
    Orbit004.oneTails,
    Orbit005.oneTails,
    Orbit006.oneTails,
    Orbit007.oneTails,
    Orbit008.oneTails,
    Orbit009.oneTails,
    Orbit010.oneTails,
    Orbit011.oneTails,
    Orbit012.oneTails,
    Orbit013.oneTails,
    Orbit014.oneTails,
    Orbit015.oneTails,
    Orbit016.oneTails,
    Orbit017.oneTails,
    Orbit018.oneTails,
    Orbit019.oneTails,
    Orbit020.oneTails,
    Orbit021.oneTails,
    Orbit022.oneTails,
    Orbit023.oneTails,
    Orbit024.oneTails,
    Orbit025.oneTails,
    Orbit026.oneTails,
    Orbit027.oneTails,
    Orbit028.oneTails,
    Orbit029.oneTails,
    Orbit030.oneTails,
    Orbit031.oneTails,
    Orbit032.oneTails,
    Orbit033.oneTails,
    Orbit034.oneTails,
    Orbit035.oneTails,
    Orbit036.oneTails,
    Orbit037.oneTails,
    Orbit038.oneTails,
    Orbit039.oneTails,
    Orbit040.oneTails,
    Orbit041.oneTails,
    Orbit042.oneTails,
    Orbit043.oneTails]

/-- Literal oneAdded selected by representative index. -/
def oneAdded : Fin 44 → Fin 7 → List (List Star.Vertex) :=
  ![Orbit000.oneAdded,
    Orbit001.oneAdded,
    Orbit002.oneAdded,
    Orbit003.oneAdded,
    Orbit004.oneAdded,
    Orbit005.oneAdded,
    Orbit006.oneAdded,
    Orbit007.oneAdded,
    Orbit008.oneAdded,
    Orbit009.oneAdded,
    Orbit010.oneAdded,
    Orbit011.oneAdded,
    Orbit012.oneAdded,
    Orbit013.oneAdded,
    Orbit014.oneAdded,
    Orbit015.oneAdded,
    Orbit016.oneAdded,
    Orbit017.oneAdded,
    Orbit018.oneAdded,
    Orbit019.oneAdded,
    Orbit020.oneAdded,
    Orbit021.oneAdded,
    Orbit022.oneAdded,
    Orbit023.oneAdded,
    Orbit024.oneAdded,
    Orbit025.oneAdded,
    Orbit026.oneAdded,
    Orbit027.oneAdded,
    Orbit028.oneAdded,
    Orbit029.oneAdded,
    Orbit030.oneAdded,
    Orbit031.oneAdded,
    Orbit032.oneAdded,
    Orbit033.oneAdded,
    Orbit034.oneAdded,
    Orbit035.oneAdded,
    Orbit036.oneAdded,
    Orbit037.oneAdded,
    Orbit038.oneAdded,
    Orbit039.oneAdded,
    Orbit040.oneAdded,
    Orbit041.oneAdded,
    Orbit042.oneAdded,
    Orbit043.oneAdded]

/-- Every stored two-credit occurrence is accepted by Lean. -/
theorem two_accepted (o : Fin 44) (i : Fin 51) :
    TwoCreditAccepted (state o) (twoComponents i) (twoCarriers i) (twoTails o i) (twoAdded o i) := by
  fin_cases o
  · exact Orbit000.two_accepted i
  · exact Orbit001.two_accepted i
  · exact Orbit002.two_accepted i
  · exact Orbit003.two_accepted i
  · exact Orbit004.two_accepted i
  · exact Orbit005.two_accepted i
  · exact Orbit006.two_accepted i
  · exact Orbit007.two_accepted i
  · exact Orbit008.two_accepted i
  · exact Orbit009.two_accepted i
  · exact Orbit010.two_accepted i
  · exact Orbit011.two_accepted i
  · exact Orbit012.two_accepted i
  · exact Orbit013.two_accepted i
  · exact Orbit014.two_accepted i
  · exact Orbit015.two_accepted i
  · exact Orbit016.two_accepted i
  · exact Orbit017.two_accepted i
  · exact Orbit018.two_accepted i
  · exact Orbit019.two_accepted i
  · exact Orbit020.two_accepted i
  · exact Orbit021.two_accepted i
  · exact Orbit022.two_accepted i
  · exact Orbit023.two_accepted i
  · exact Orbit024.two_accepted i
  · exact Orbit025.two_accepted i
  · exact Orbit026.two_accepted i
  · exact Orbit027.two_accepted i
  · exact Orbit028.two_accepted i
  · exact Orbit029.two_accepted i
  · exact Orbit030.two_accepted i
  · exact Orbit031.two_accepted i
  · exact Orbit032.two_accepted i
  · exact Orbit033.two_accepted i
  · exact Orbit034.two_accepted i
  · exact Orbit035.two_accepted i
  · exact Orbit036.two_accepted i
  · exact Orbit037.two_accepted i
  · exact Orbit038.two_accepted i
  · exact Orbit039.two_accepted i
  · exact Orbit040.two_accepted i
  · exact Orbit041.two_accepted i
  · exact Orbit042.two_accepted i
  · exact Orbit043.two_accepted i

/-- Every stored one-credit occurrence is accepted by Lean. -/
theorem one_accepted (o : Fin 44) (i : Fin 7) :
    OneCreditAccepted (state o) (oneComponents i) (oneTails o i) (oneAdded o i) := by
  fin_cases o
  · exact Orbit000.one_accepted i
  · exact Orbit001.one_accepted i
  · exact Orbit002.one_accepted i
  · exact Orbit003.one_accepted i
  · exact Orbit004.one_accepted i
  · exact Orbit005.one_accepted i
  · exact Orbit006.one_accepted i
  · exact Orbit007.one_accepted i
  · exact Orbit008.one_accepted i
  · exact Orbit009.one_accepted i
  · exact Orbit010.one_accepted i
  · exact Orbit011.one_accepted i
  · exact Orbit012.one_accepted i
  · exact Orbit013.one_accepted i
  · exact Orbit014.one_accepted i
  · exact Orbit015.one_accepted i
  · exact Orbit016.one_accepted i
  · exact Orbit017.one_accepted i
  · exact Orbit018.one_accepted i
  · exact Orbit019.one_accepted i
  · exact Orbit020.one_accepted i
  · exact Orbit021.one_accepted i
  · exact Orbit022.one_accepted i
  · exact Orbit023.one_accepted i
  · exact Orbit024.one_accepted i
  · exact Orbit025.one_accepted i
  · exact Orbit026.one_accepted i
  · exact Orbit027.one_accepted i
  · exact Orbit028.one_accepted i
  · exact Orbit029.one_accepted i
  · exact Orbit030.one_accepted i
  · exact Orbit031.one_accepted i
  · exact Orbit032.one_accepted i
  · exact Orbit033.one_accepted i
  · exact Orbit034.one_accepted i
  · exact Orbit035.one_accepted i
  · exact Orbit036.one_accepted i
  · exact Orbit037.one_accepted i
  · exact Orbit038.one_accepted i
  · exact Orbit039.one_accepted i
  · exact Orbit040.one_accepted i
  · exact Orbit041.one_accepted i
  · exact Orbit042.one_accepted i
  · exact Orbit043.one_accepted i

end Gallai.Certificate.ZeroSyndrome.Catalogue
