/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.ZeroSyndromeRecord
import Mathlib.Data.Fin.VecNotation

/-! # Zero-syndrome ordered catalogue interfaces

Generated by scripts/import_zero_syndrome_catalogue.py from SHA256
32c2c172fa37de8b8de229fb2f531543e2e9274cfa5316796c582c6989ebdd59.
Literal data; ordinary Lean decision reduction checks acceptance.
Coverage of arbitrary labelled states is a separate obligation.
-/

namespace Gallai.Certificate.ZeroSyndrome.Catalogue

/-- The component labels of each two-credit interface. -/
def twoComponents : Fin 51 → Labels :=
  ![![0, 0, 0, 0],
    ![0, 0, 0, 0],
    ![0, 0, 0, 0],
    ![0, 0, 0, 0],
    ![0, 0, 0, 0],
    ![0, 0, 0, 0],
    ![0, 0, 0, 0],
    ![0, 0, 0, 0],
    ![0, 0, 0, 0],
    ![0, 0, 0, 0],
    ![0, 0, 0, 3],
    ![0, 0, 0, 3],
    ![0, 0, 0, 3],
    ![0, 0, 0, 3],
    ![0, 0, 2, 0],
    ![0, 0, 2, 0],
    ![0, 0, 2, 0],
    ![0, 0, 2, 0],
    ![0, 0, 2, 2],
    ![0, 0, 2, 2],
    ![0, 0, 2, 2],
    ![0, 0, 2, 2],
    ![0, 0, 2, 3],
    ![0, 0, 2, 3],
    ![0, 1, 0, 0],
    ![0, 1, 0, 0],
    ![0, 1, 0, 0],
    ![0, 1, 0, 0],
    ![0, 1, 0, 1],
    ![0, 1, 0, 1],
    ![0, 1, 0, 1],
    ![0, 1, 0, 1],
    ![0, 1, 0, 3],
    ![0, 1, 0, 3],
    ![0, 1, 1, 0],
    ![0, 1, 1, 0],
    ![0, 1, 1, 0],
    ![0, 1, 1, 0],
    ![0, 1, 1, 1],
    ![0, 1, 1, 1],
    ![0, 1, 1, 1],
    ![0, 1, 1, 1],
    ![0, 1, 1, 3],
    ![0, 1, 1, 3],
    ![0, 1, 2, 0],
    ![0, 1, 2, 0],
    ![0, 1, 2, 1],
    ![0, 1, 2, 1],
    ![0, 1, 2, 2],
    ![0, 1, 2, 2],
    ![0, 1, 2, 3]]

/-- The matching carrier labels of each two-credit interface. -/
def twoCarriers : Fin 51 → Labels :=
  ![![0, 0, 2, 2],
    ![0, 0, 2, 3],
    ![0, 1, 0, 1],
    ![0, 1, 0, 3],
    ![0, 1, 1, 0],
    ![0, 1, 1, 3],
    ![0, 1, 2, 0],
    ![0, 1, 2, 1],
    ![0, 1, 2, 2],
    ![0, 1, 2, 3],
    ![0, 0, 2, 3],
    ![0, 1, 0, 3],
    ![0, 1, 1, 3],
    ![0, 1, 2, 3],
    ![0, 0, 2, 3],
    ![0, 1, 2, 0],
    ![0, 1, 2, 1],
    ![0, 1, 2, 3],
    ![0, 0, 2, 2],
    ![0, 0, 2, 3],
    ![0, 1, 2, 2],
    ![0, 1, 2, 3],
    ![0, 0, 2, 3],
    ![0, 1, 2, 3],
    ![0, 1, 0, 3],
    ![0, 1, 2, 0],
    ![0, 1, 2, 2],
    ![0, 1, 2, 3],
    ![0, 1, 0, 1],
    ![0, 1, 0, 3],
    ![0, 1, 2, 1],
    ![0, 1, 2, 3],
    ![0, 1, 0, 3],
    ![0, 1, 2, 3],
    ![0, 1, 1, 0],
    ![0, 1, 1, 3],
    ![0, 1, 2, 0],
    ![0, 1, 2, 3],
    ![0, 1, 1, 3],
    ![0, 1, 2, 1],
    ![0, 1, 2, 2],
    ![0, 1, 2, 3],
    ![0, 1, 1, 3],
    ![0, 1, 2, 3],
    ![0, 1, 2, 0],
    ![0, 1, 2, 3],
    ![0, 1, 2, 1],
    ![0, 1, 2, 3],
    ![0, 1, 2, 2],
    ![0, 1, 2, 3],
    ![0, 1, 2, 3]]

/-- The component labels for the one-credit separated branch. -/
def oneComponents : Fin 7 → Labels :=
  ![![0, 0, 2, 3],
    ![0, 1, 0, 3],
    ![0, 1, 1, 3],
    ![0, 1, 2, 0],
    ![0, 1, 2, 1],
    ![0, 1, 2, 2],
    ![0, 1, 2, 3]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every listed two-credit interface is legal. -/
theorem two_interface (i : Fin 51) : (twoComponents i, twoCarriers i) ∈ interfaces := by
  apply (mem_interfaces _ _).mpr
  revert i
  decide

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every listed one-credit interface has at least three components. -/
theorem one_interface (i : Fin 7) : oneComponents i ∈ separatedPartitions := by
  revert i
  decide

end Gallai.Certificate.ZeroSyndrome.Catalogue
