/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.CompletedStar

/-! # Completed-star catalogue orbit 015

Generated by scripts/import_completed_star_catalogue.py from certificate SHA256
4dbb85f7bef9f06a6b4701c7bd611c60507ecedfcf83c46b2c6b1a44828f513d.
Literal data only; acceptance is checked by ordinary Lean decision reduction.
This file does not assert orbit or labelled-universe coverage.
-/

namespace Gallai.Certificate.CompletedStar.Catalogue.Orbit015

open Star.Vertex

/-- The original five rows of this representative. -/
def state : State := ![3, 0, 0, 5, 9]

/-- Ordered replacement words at each of the ten interfaces. -/
def replacements : Fin 10 → List (List Star.Vertex) :=
  ![[[p, x, q], [r, c, d, s]],
    [[p, c, r], [q, x, d, s]],
    [[p, d, s], [q, x, c, r]],
    [[p, c], [q, x], [r, c, x, d, s]],
    [[p, c], [r, c], [q, x, d, s]],
    [[p, c], [s, d], [q, x, c, r]],
    [[q, x], [r, c], [p, c, x, d, s]],
    [[q, x], [s, d], [p, d, x, c, r]],
    [[r, c], [s, d], [p, x, q]],
    [[p, c], [q, x], [r, c], [s, d, x]]]

/-- Added words, preserving distinct occurrences. -/
def added : Fin 10 → List (List Star.Vertex) :=
  ![[[a, b, x, c], [a, x, d, p, c]],
    [[a, b, x, c], [a, x, p, d, c]],
    [[a, b, x, d], [a, x, p, c, d]],
    [[a, b, x], [a, x, p, d, c]],
    [[a, b, x, c], [a, x, p, d, c]],
    [[a, b, x, d], [a, x, p, d, c]],
    [[a, b, x], [a, x, p, d, c]],
    [[a, b, x], [a, x, p, c, d]],
    [[a, b, x, c, d], [a, x, d, p, c]],
    [[a, b, x, c], [a, x, p, d, c]]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every interface at this representative meets the actual finite contract. -/
theorem accepted (i : Fin 10) : AcceptedRecord state i (replacements i) (added i) := by
  revert i
  decide

end Gallai.Certificate.CompletedStar.Catalogue.Orbit015
