/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.CompletedStar

/-! # Completed-star catalogue orbit 005

Generated by scripts/import_completed_star_catalogue.py from certificate SHA256
4dbb85f7bef9f06a6b4701c7bd611c60507ecedfcf83c46b2c6b1a44828f513d.
Literal data only; acceptance is checked by ordinary Lean decision reduction.
This file does not assert orbit or labelled-universe coverage.
-/

namespace Gallai.Certificate.CompletedStar.Catalogue.Orbit005

open Star.Vertex

/-- The original five rows of this representative. -/
def state : State := ![0, 0, 15, 3, 3]

/-- Ordered replacement words at each of the ten interfaces. -/
def replacements : Fin 10 → List (List Star.Vertex) :=
  ![[[p, b, q], [r, b, s]],
    [[p, b, r], [q, b, s]],
    [[p, b, s], [q, b, r]],
    [[p, b], [q, b], [r, b, s]],
    [[p, b], [r, b], [q, b, s]],
    [[p, b], [s, b], [q, b, r]],
    [[q, b], [r, b], [p, b, s]],
    [[q, b], [s, b], [p, b, r]],
    [[r, b], [s, b], [p, b, q]],
    [[p, b], [q, b], [r, b], [s, b]]]

/-- Added words, preserving distinct occurrences. -/
def added : Fin 10 → List (List Star.Vertex) :=
  ![[[a, b, x, c, d, p], [a, x, d, q, c, p]],
    [[a, b, x, c, d, p], [a, x, d, q, c, p]],
    [[a, b, x, c, d, p], [a, x, d, q, c, p]],
    [[a, b, x, c, d, p], [a, x, d, q, c, p]],
    [[a, b, x, c, d, p], [a, x, d, q, c, p]],
    [[a, b, x, c, d, p], [a, x, d, q, c, p]],
    [[a, b, x, c, d, p], [a, x, d, q, c, p]],
    [[a, b, x, c, d, p], [a, x, d, q, c, p]],
    [[a, b, x, c, d, p], [a, x, d, q, c, p]],
    [[a, b, x, c, d, p], [a, x, d, q, c, p]]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every interface at this representative meets the actual finite contract. -/
theorem accepted (i : Fin 10) : AcceptedRecord state i (replacements i) (added i) := by
  revert i
  decide

end Gallai.Certificate.CompletedStar.Catalogue.Orbit005
