/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.CompletedStar

/-! # Completed-star catalogue orbit 006

Generated by scripts/import_completed_star_catalogue.py from certificate SHA256
4dbb85f7bef9f06a6b4701c7bd611c60507ecedfcf83c46b2c6b1a44828f513d.
Literal data only; acceptance is checked by ordinary Lean decision reduction.
This file does not assert orbit or labelled-universe coverage.
-/

namespace Gallai.Certificate.CompletedStar.Catalogue.Orbit006

open Star.Vertex

/-- The original five rows of this representative. -/
def state : State := ![0, 0, 15, 15, 15]

/-- Ordered replacement words at each of the ten interfaces. -/
def replacements : Fin 10 → List (List Star.Vertex) :=
  ![[[p, b, q], [r, c, d, s]],
    [[p, b, r], [q, c, d, s]],
    [[p, b, s], [q, c, d, r]],
    [[p, b], [q, b], [r, c, d, s]],
    [[p, b], [r, b], [q, c, d, s]],
    [[p, b], [s, b], [q, c, d, r]],
    [[q, b], [r, b], [p, c, d, s]],
    [[q, b], [s, b], [p, c, d, r]],
    [[r, b], [s, b], [p, c, d, q]],
    [[p, b], [q, b], [r, b], [s, c, d, x]]]

/-- Added words, preserving distinct occurrences. -/
def added : Fin 10 → List (List Star.Vertex) :=
  ![[[a, b, r, d, x, c, p], [a, x, b, s, c, q, d, p]],
    [[a, b, q, d, x, c, p], [a, x, b, s, c, r, d, p]],
    [[a, b, q, d, x, c, p], [a, x, b, r, c, s, d, p]],
    [[a, b, r, d, x, c, p], [a, x, b, s, c, q, d, p]],
    [[a, b, q, d, x, c, p], [a, x, b, s, c, r, d, p]],
    [[a, b, q, d, x, c, p], [a, x, b, r, c, s, d, p]],
    [[a, b, p, d, x, c, q], [a, x, b, s, c, r, d, q]],
    [[a, b, p, d, x, c, q], [a, x, b, r, c, s, d, q]],
    [[a, b, p, d, x, c, r], [a, x, b, q, c, s, d, r]],
    [[b, a, x, c, p, d, q], [q, c, r, d, s, b, x]]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every interface at this representative meets the actual finite contract. -/
theorem accepted (i : Fin 10) : AcceptedRecord state i (replacements i) (added i) := by
  revert i
  decide

end Gallai.Certificate.CompletedStar.Catalogue.Orbit006
