/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.CompletedStar

/-! # Completed-star catalogue orbit 039

Generated by scripts/import_completed_star_catalogue.py from certificate SHA256
4dbb85f7bef9f06a6b4701c7bd611c60507ecedfcf83c46b2c6b1a44828f513d.
Literal data only; acceptance is checked by ordinary Lean decision reduction.
This file does not assert orbit or labelled-universe coverage.
-/

namespace Gallai.Certificate.CompletedStar.Catalogue.Orbit039

open Star.Vertex

/-- The original five rows of this representative. -/
def state : State := ![3, 5, 5, 5, 9]

/-- Ordered replacement words at each of the ten interfaces. -/
def replacements : Fin 10 → List (List Star.Vertex) :=
  ![[[p, x, q], [r, c, d, s]],
    [[p, a, r], [q, x, d, s]],
    [[p, d, s], [q, x, a, r]],
    [[p, a], [q, x], [r, a, x, d, s]],
    [[p, a], [r, a], [q, x, d, s]],
    [[p, a], [s, d], [q, x, a, r]],
    [[q, x], [r, a], [p, x, d, s]],
    [[q, x], [s, d], [p, x, a, r]],
    [[r, a], [s, d], [p, x, q]],
    [[p, a], [q, x], [r, a], [s, d, x]]]

/-- Added words, preserving distinct occurrences. -/
def added : Fin 10 → List (List Star.Vertex) :=
  ![[[c, p, a, b, x, d], [c, x, a, r, b, p, d]],
    [[a, b, p, x, c, d], [a, x, b, r, c, p, d]],
    [[a, b, p, c, x, d], [a, p, x, b, r, c, d]],
    [[a, b, p, x, c, d], [d, p, c, r, b, x]],
    [[a, b, p, x, c, d], [a, x, b, r, c, p, d]],
    [[a, b, p, d, x, c, r], [d, c, p, x, b, r]],
    [[a, b, x, c, p, d], [d, c, r, b, p, a, x]],
    [[a, b, p, c, x, d], [a, p, d, c, r, b, x]],
    [[a, b, p, d, x, c, r], [d, c, p, a, x, b, r]],
    [[a, b, p, x, c, d], [a, x, b, r, c, p, d]]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every interface at this representative meets the actual finite contract. -/
theorem accepted (i : Fin 10) : AcceptedRecord state i (replacements i) (added i) := by
  revert i
  decide

end Gallai.Certificate.CompletedStar.Catalogue.Orbit039
