/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.CompletedStar

/-! # Completed-star catalogue orbit 048

Generated by scripts/import_completed_star_catalogue.py from certificate SHA256
4dbb85f7bef9f06a6b4701c7bd611c60507ecedfcf83c46b2c6b1a44828f513d.
Literal data only; acceptance is checked by ordinary Lean decision reduction.
This file does not assert orbit or labelled-universe coverage.
-/

namespace Gallai.Certificate.CompletedStar.Catalogue.Orbit048

open Star.Vertex

/-- The original five rows of this representative. -/
def state : State := ![15, 0, 0, 0, 0]

/-- Ordered replacement words at each of the ten interfaces. -/
def replacements : Fin 10 → List (List Star.Vertex) :=
  ![[[p, x, q], [r, x, s]],
    [[p, x, r], [q, x, s]],
    [[p, x, s], [q, x, r]],
    [[p, x], [q, x], [r, x, s]],
    [[p, x], [r, x], [q, x, s]],
    [[p, x], [s, x], [q, x, r]],
    [[q, x], [r, x], [p, x, s]],
    [[q, x], [s, x], [p, x, r]],
    [[r, x], [s, x], [p, x, q]],
    [[p, x], [q, x], [r, x], [s, x]]]

/-- Added words, preserving distinct occurrences. -/
def added : Fin 10 → List (List Star.Vertex) :=
  ![[[a, b, x, c], [a, x, d, c]],
    [[a, b, x, c], [a, x, d, c]],
    [[a, b, x, c], [a, x, d, c]],
    [[a, b, x, c], [a, x, d, c]],
    [[a, b, x, c], [a, x, d, c]],
    [[a, b, x, c], [a, x, d, c]],
    [[a, b, x, c], [a, x, d, c]],
    [[a, b, x, c], [a, x, d, c]],
    [[a, b, x, c], [a, x, d, c]],
    [[a, b, x, c], [a, x, d, c]]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every interface at this representative meets the actual finite contract. -/
theorem accepted (i : Fin 10) : AcceptedRecord state i (replacements i) (added i) := by
  revert i
  decide

end Gallai.Certificate.CompletedStar.Catalogue.Orbit048
