/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.CompletedStar

/-! # Completed-star catalogue orbit 008

Generated by scripts/import_completed_star_catalogue.py from certificate SHA256
4dbb85f7bef9f06a6b4701c7bd611c60507ecedfcf83c46b2c6b1a44828f513d.
Literal data only; acceptance is checked by ordinary Lean decision reduction.
This file does not assert orbit or labelled-universe coverage.
-/

namespace Gallai.Certificate.CompletedStar.Catalogue.Orbit008

open Star.Vertex

/-- The original five rows of this representative. -/
def state : State := ![0, 3, 3, 5, 10]

/-- Ordered replacement words at each of the ten interfaces. -/
def replacements : Fin 10 → List (List Star.Vertex) :=
  ![[[p, a, q], [r, c, d, s]],
    [[p, c, r], [q, d, s]],
    [[p, c, d, s], [q, a, x, c, r]],
    [[p, a], [q, a], [r, c, d, s]],
    [[p, a], [r, c], [q, d, s]],
    [[p, a], [s, d], [q, d, c, r]],
    [[q, a], [r, c], [p, c, d, s]],
    [[q, a], [s, d], [p, c, r]],
    [[r, c], [s, d], [p, a, q]],
    [[p, a], [q, a], [r, c], [s, d]]]

/-- Added words, preserving distinct occurrences. -/
def added : Fin 10 → List (List Star.Vertex) :=
  ![[[a, b, x, c], [a, x, d, q, b, p, c]],
    [[c, x, a, b, p], [c, d, x, b, q, a, p]],
    [[a, b, q], [a, p, b, x, d, q]],
    [[a, b, x, c], [a, x, d, q, b, p, c]],
    [[a, b, x, c, d], [c, p, b, q, a, x, d]],
    [[a, b, x, c], [c, p, b, q, a, x, d]],
    [[a, b, x, d], [c, x, a, p, b, q, d]],
    [[a, b, x, d, c], [c, x, a, p, b, q, d]],
    [[a, b, x, c, d], [a, x, d, q, b, p, c]],
    [[a, b, x, c, d], [a, x, d, q, b, p, c]]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every interface at this representative meets the actual finite contract. -/
theorem accepted (i : Fin 10) : AcceptedRecord state i (replacements i) (added i) := by
  revert i
  decide

end Gallai.Certificate.CompletedStar.Catalogue.Orbit008
