/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.CompletedStar

/-! # Completed-star catalogue orbit 057

Generated by scripts/import_completed_star_catalogue.py from certificate SHA256
4dbb85f7bef9f06a6b4701c7bd611c60507ecedfcf83c46b2c6b1a44828f513d.
Literal data only; acceptance is checked by ordinary Lean decision reduction.
This file does not assert orbit or labelled-universe coverage.
-/

namespace Gallai.Certificate.CompletedStar.Catalogue.Orbit057

open Star.Vertex

/-- The original five rows of this representative. -/
def state : State := ![15, 3, 3, 5, 5]

/-- Ordered replacement words at each of the ten interfaces. -/
def replacements : Fin 10 → List (List Star.Vertex) :=
  ![[[p, x, q], [r, x, s]],
    [[p, x, r], [q, x, s]],
    [[p, x, s], [q, x, r]],
    [[p, a], [q, x, a], [r, x, s]],
    [[p, a], [r, x, a], [q, x, s]],
    [[p, a], [s, x, a], [q, x, r]],
    [[q, a], [r, x, a], [p, x, s]],
    [[q, a], [s, x, a], [p, x, r]],
    [[r, c], [s, x, a], [p, x, q]],
    [[p, a], [q, a], [r, x, a], [s, x, b]]]

/-- Added words, preserving distinct occurrences. -/
def added : Fin 10 → List (List Star.Vertex) :=
  ![[[q, a, b, p, c, x, d, r], [q, b, x, a, p, d, c, r]],
    [[q, a, b, p, c, x, d, r], [q, b, x, a, p, d, c, r]],
    [[q, a, b, p, c, x, d, r], [q, b, x, a, p, d, c, r]],
    [[a, b, p, c, x, d, r], [a, q, b, x, p, d, c, r]],
    [[a, b, p, c, x, d, r], [a, q, b, x, p, d, c, r]],
    [[a, b, p, c, x, d, r], [a, q, b, x, p, d, c, r]],
    [[a, b, p, c, d, x, q], [a, p, d, r, c, x, b, q]],
    [[a, b, p, c, d, x, q], [a, p, d, r, c, x, b, q]],
    [[a, b, p, c, d, x, r], [c, x, b, q, a, p, d, r]],
    [[a, b, p, c, x, d, r], [b, q, x, p, d, c, r]]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every interface at this representative meets the actual finite contract. -/
theorem accepted (i : Fin 10) : AcceptedRecord state i (replacements i) (added i) := by
  revert i
  decide

end Gallai.Certificate.CompletedStar.Catalogue.Orbit057
