/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.CompletedStar

/-! # Completed-star catalogue orbit 056

Generated by scripts/import_completed_star_catalogue.py from certificate SHA256
4dbb85f7bef9f06a6b4701c7bd611c60507ecedfcf83c46b2c6b1a44828f513d.
Literal data only; acceptance is checked by ordinary Lean decision reduction.
This file does not assert orbit or labelled-universe coverage.
-/

namespace Gallai.Certificate.CompletedStar.Catalogue.Orbit056

open Star.Vertex

/-- The original five rows of this representative. -/
def state : State := ![15, 3, 3, 3, 3]

/-- Ordered replacement words at each of the ten interfaces. -/
def replacements : Fin 10 → List (List Star.Vertex) :=
  ![[[p, a, b, x, q], [r, x, s]],
    [[p, x, r], [q, a, b, x, s]],
    [[p, x, s], [q, a, b, x, r]],
    [[p, a], [q, b, x, c], [r, x, s]],
    [[p, a], [r, x, a], [q, c, x, s]],
    [[p, a], [s, x, a], [q, c, x, r]],
    [[q, a], [r, x, a], [p, c, x, s]],
    [[q, a], [s, x, a], [p, c, x, r]],
    [[r, x], [s, x], [p, a, b, x, q]],
    [[p, a], [q, a], [r, x, a], [s, x, c, d]]]

/-- Added words, preserving distinct occurrences. -/
def added : Fin 10 → List (List Star.Vertex) :=
  ![[[a, q, c, d, x, p, b], [a, x, c, p, d, q, b]],
    [[a, p, c, d, x, q, b], [a, x, c, q, d, p, b]],
    [[a, p, c, d, x, q, b], [a, x, c, q, d, p, b]],
    [[b, a, q, d, x, p, c], [a, x, q, c, d, p, b]],
    [[a, b, p, x, q, d, c], [a, q, b, x, d, p, c]],
    [[a, b, p, x, q, d, c], [a, q, b, x, d, p, c]],
    [[a, b, p, d, x, q, c], [a, p, x, b, q, d, c]],
    [[a, b, p, d, x, q, c], [a, p, x, b, q, d, c]],
    [[a, q, c, d, x, p, b], [a, x, c, p, d, q, b]],
    [[a, b, p, d, x, q, c], [c, p, x, b, q, d]]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every interface at this representative meets the actual finite contract. -/
theorem accepted (i : Fin 10) : AcceptedRecord state i (replacements i) (added i) := by
  revert i
  decide

end Gallai.Certificate.CompletedStar.Catalogue.Orbit056
