/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.CompletedStar

/-! # Completed-star catalogue orbit 031

Generated by scripts/import_completed_star_catalogue.py from certificate SHA256
4dbb85f7bef9f06a6b4701c7bd611c60507ecedfcf83c46b2c6b1a44828f513d.
Literal data only; acceptance is checked by ordinary Lean decision reduction.
This file does not assert orbit or labelled-universe coverage.
-/

namespace Gallai.Certificate.CompletedStar.Catalogue.Orbit031

open Star.Vertex

/-- The original five rows of this representative. -/
def state : State := ![3, 3, 5, 3, 9]

/-- Ordered replacement words at each of the ten interfaces. -/
def replacements : Fin 10 → List (List Star.Vertex) :=
  ![[[p, a, q], [r, b, x, d, s]],
    [[p, b, r], [q, x, d, s]],
    [[p, d, s], [q, x, b, r]],
    [[p, a], [q, a], [r, b, x, d, s]],
    [[p, a], [r, b], [q, x, d, s]],
    [[p, a], [s, d], [q, x, b, r]],
    [[q, a], [r, b], [p, x, d, s]],
    [[q, a], [s, d], [p, x, b, r]],
    [[r, b], [s, d], [p, x, q]],
    [[p, a], [q, a], [r, b], [s, d, x, a]]]

/-- Added words, preserving distinct occurrences. -/
def added : Fin 10 → List (List Star.Vertex) :=
  ![[[a, b, p, c, x, q], [a, x, p, d, c, q]],
    [[b, a, p, x, c, d], [b, x, a, q, c, p, d]],
    [[b, a, p, c, x, d], [b, p, x, a, q, c, d]],
    [[a, b, p, c, x, q], [a, x, p, d, c, q]],
    [[a, b, p, x, c, d], [b, x, a, q, c, p, d]],
    [[b, a, x, c, p, d], [a, q, c, d, x, p, b]],
    [[a, b, p, c, x, q], [b, x, a, p, d, c, q]],
    [[b, a, p, c, x, d], [a, x, q, c, d, p, b]],
    [[b, a, p, d, x, c, q], [d, c, p, b, x, a, q]],
    [[a, b, p, c, x, q], [b, x, p, d, c, q]]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every interface at this representative meets the actual finite contract. -/
theorem accepted (i : Fin 10) : AcceptedRecord state i (replacements i) (added i) := by
  revert i
  decide

end Gallai.Certificate.CompletedStar.Catalogue.Orbit031
