/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.CompletedStar

/-! # Completed-star catalogue orbit 009

Generated by scripts/import_completed_star_catalogue.py from certificate SHA256
4dbb85f7bef9f06a6b4701c7bd611c60507ecedfcf83c46b2c6b1a44828f513d.
Literal data only; acceptance is checked by ordinary Lean decision reduction.
This file does not assert orbit or labelled-universe coverage.
-/

namespace Gallai.Certificate.CompletedStar.Catalogue.Orbit009

open Star.Vertex

/-- The original five rows of this representative. -/
def state : State := ![0, 3, 5, 3, 10]

/-- Ordered replacement words at each of the ten interfaces. -/
def replacements : Fin 10 → List (List Star.Vertex) :=
  ![[[p, a, q], [r, b, x, d, s]],
    [[p, b, r], [q, d, s]],
    [[p, c, d, s], [q, a, b, r]],
    [[p, a], [q, a], [r, b, x, d, s]],
    [[p, a], [r, b], [q, d, s]],
    [[p, a], [s, d], [q, a, b, r]],
    [[q, a], [r, b], [p, c, d, s]],
    [[q, a], [s, d], [p, b, r]],
    [[r, b], [s, d], [p, a, q]],
    [[p, a], [q, a], [r, b], [s, d]]]

/-- Added words, preserving distinct occurrences. -/
def added : Fin 10 → List (List Star.Vertex) :=
  ![[[a, b, p, c, d], [a, x, c, q, d]],
    [[b, a, x, c, p], [b, x, d, c, q, a, p]],
    [[c, x, a, p], [c, q, d, x, b, p]],
    [[a, b, p, c, d], [a, x, c, q, d]],
    [[a, b, x, c, d], [b, p, c, q, a, x, d]],
    [[a, x, c, d, q], [d, x, b, p, c, q]],
    [[a, b, x, c], [b, p, a, x, d, q, c]],
    [[b, a, x, c, d], [a, p, c, q, d, x, b]],
    [[a, b, x, c, d], [a, x, d, q, c, p, b]],
    [[a, b, x, c, d], [a, x, d, q, c, p, b]]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every interface at this representative meets the actual finite contract. -/
theorem accepted (i : Fin 10) : AcceptedRecord state i (replacements i) (added i) := by
  revert i
  decide

end Gallai.Certificate.CompletedStar.Catalogue.Orbit009
