/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.CompletedStar

/-! # Completed-star catalogue orbit 059

Generated by scripts/import_completed_star_catalogue.py from certificate SHA256
4dbb85f7bef9f06a6b4701c7bd611c60507ecedfcf83c46b2c6b1a44828f513d.
Literal data only; acceptance is checked by ordinary Lean decision reduction.
This file does not assert orbit or labelled-universe coverage.
-/

namespace Gallai.Certificate.CompletedStar.Catalogue.Orbit059

open Star.Vertex

/-- The original five rows of this representative. -/
def state : State := ![15, 3, 3, 15, 15]

/-- Ordered replacement words at each of the ten interfaces. -/
def replacements : Fin 10 → List (List Star.Vertex) :=
  ![[[p, x, q], [r, c, d, x, s]],
    [[p, x, r], [q, c, d, x, s]],
    [[p, x, s], [q, c, d, x, r]],
    [[p, a], [q, x, a], [r, c, d, x, s]],
    [[p, a], [r, x, a], [q, c, d, x, s]],
    [[p, a], [s, x, a], [q, c, d, x, r]],
    [[q, a], [r, x, a], [p, c, d, x, s]],
    [[q, a], [s, x, a], [p, c, d, x, r]],
    [[r, c], [s, x, a], [p, c, d, x, q]],
    [[p, a], [q, a], [r, x, a], [s, c, d, x, b]]]

/-- Added words, preserving distinct occurrences. -/
def added : Fin 10 → List (List Star.Vertex) :=
  ![[[r, x, a, b, p, c, q, d, s], [r, d, p, a, q, b, x, c, s]],
    [[r, c, p, a, b, x, q, d, s], [r, d, p, b, q, a, x, c, s]],
    [[r, c, p, a, b, x, q, d, s], [r, d, p, b, q, a, x, c, s]],
    [[a, b, p, d, q, c, x, r], [a, q, b, x, p, c, s, d, r]],
    [[a, b, p, c, x, q, d, r], [a, q, b, x, p, d, s, c, r]],
    [[a, b, p, c, x, q, d, r], [a, q, b, x, p, d, s, c, r]],
    [[a, b, p, d, q, x, c, r], [a, p, x, b, q, c, s, d, r]],
    [[a, b, p, d, q, x, c, r], [a, p, x, b, q, c, s, d, r]],
    [[a, b, p, x, c, q, d, r], [c, s, d, p, a, q, b, x, r]],
    [[a, b, p, c, x, q, d, s], [b, q, c, r, d, p, x, s]]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every interface at this representative meets the actual finite contract. -/
theorem accepted (i : Fin 10) : AcceptedRecord state i (replacements i) (added i) := by
  revert i
  decide

end Gallai.Certificate.CompletedStar.Catalogue.Orbit059
