/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.CompletedStar

/-! # Completed-star catalogue orbit 038

Generated by scripts/import_completed_star_catalogue.py from certificate SHA256
4dbb85f7bef9f06a6b4701c7bd611c60507ecedfcf83c46b2c6b1a44828f513d.
Literal data only; acceptance is checked by ordinary Lean decision reduction.
This file does not assert orbit or labelled-universe coverage.
-/

namespace Gallai.Certificate.CompletedStar.Catalogue.Orbit038

open Star.Vertex

/-- The original five rows of this representative. -/
def state : State := ![3, 3, 15, 15, 15]

/-- Ordered replacement words at each of the ten interfaces. -/
def replacements : Fin 10 → List (List Star.Vertex) :=
  ![[[p, a, q], [r, b, x, c, d, s]],
    [[p, b, r], [q, c, x, d, s]],
    [[p, b, s], [q, c, x, d, r]],
    [[p, a], [q, a], [r, b, x, c, d, s]],
    [[p, a], [r, b], [q, b, x, c, d, s]],
    [[p, a], [s, b], [q, b, x, c, d, r]],
    [[q, a], [r, b], [p, b, x, c, d, s]],
    [[q, a], [s, b], [p, b, x, c, d, r]],
    [[r, b], [s, b], [p, c, d, x, q]],
    [[p, a], [q, a], [r, b], [s, c, d, x, b]]]

/-- Added words, preserving distinct occurrences. -/
def added : Fin 10 → List (List Star.Vertex) :=
  ![[[a, b, p, c, q, x, d, r], [a, x, p, d, q, b, s, c, r]],
    [[r, c, d, p, x, q, a, b, s], [r, d, q, b, x, a, p, c, s]],
    [[r, b, a, q, x, p, d, c, s], [r, c, p, a, x, b, q, d, s]],
    [[a, b, p, c, q, x, d, r], [a, x, p, d, q, b, s, c, r]],
    [[a, b, p, d, x, q, c, r], [b, s, c, p, x, a, q, d, r]],
    [[a, b, p, d, x, q, c, s], [b, r, c, p, x, a, q, d, s]],
    [[a, b, q, d, x, p, c, r], [b, s, c, q, x, a, p, d, r]],
    [[a, b, q, d, x, p, c, s], [b, r, c, q, x, a, p, d, s]],
    [[r, c, q, a, b, x, p, d, s], [r, d, q, b, p, a, x, c, s]],
    [[a, b, p, c, x, q, d, r], [a, x, p, d, s, b, q, c, r]]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every interface at this representative meets the actual finite contract. -/
theorem accepted (i : Fin 10) : AcceptedRecord state i (replacements i) (added i) := by
  revert i
  decide

end Gallai.Certificate.CompletedStar.Catalogue.Orbit038
