/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.CompletedStar

/-! # Completed-star catalogue orbit 022

Generated by scripts/import_completed_star_catalogue.py from certificate SHA256
4dbb85f7bef9f06a6b4701c7bd611c60507ecedfcf83c46b2c6b1a44828f513d.
Literal data only; acceptance is checked by ordinary Lean decision reduction.
This file does not assert orbit or labelled-universe coverage.
-/

namespace Gallai.Certificate.CompletedStar.Catalogue.Orbit022

open Star.Vertex

/-- The original five rows of this representative. -/
def state : State := ![3, 0, 5, 6, 15]

/-- Ordered replacement words at each of the ten interfaces. -/
def replacements : Fin 10 → List (List Star.Vertex) :=
  ![[[p, d, q], [r, b, x, d, s]],
    [[p, b, r], [q, x, d, s]],
    [[p, d, s], [q, x, b, r]],
    [[p, b], [q, c], [r, b, x, d, s]],
    [[p, b], [r, b], [q, x, d, s]],
    [[p, b], [s, d], [q, x, d, r]],
    [[q, c], [r, b], [p, x, d, s]],
    [[q, c], [s, d], [p, x, d, r]],
    [[r, b], [s, d], [p, x, d, q]],
    [[p, b], [q, c], [r, b], [s, d, x, a]]]

/-- Added words, preserving distinct occurrences. -/
def added : Fin 10 → List (List Star.Vertex) :=
  ![[[b, a, x, c, d], [b, p, x, q, c, r, d]],
    [[a, b, x, c, d, q], [a, x, p, d, r, c, q]],
    [[b, a, x, c, d, q], [b, p, x, d, r, c, q]],
    [[b, a, x, c, d, p], [c, r, d, q, x, p]],
    [[a, b, x, c, d, q], [a, x, p, d, r, c, q]],
    [[a, b, x, c, d], [a, x, p, d, q, c, r, b]],
    [[a, b, x, q, d, c], [a, x, c, r, d, p, b]],
    [[a, b, x, c, d], [a, x, q, d, p, b, r, c]],
    [[a, b, x, c, d], [a, x, q, c, r, d, p, b]],
    [[a, b, x, c, d, p], [c, r, d, q, x, p]]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every interface at this representative meets the actual finite contract. -/
theorem accepted (i : Fin 10) : AcceptedRecord state i (replacements i) (added i) := by
  revert i
  decide

end Gallai.Certificate.CompletedStar.Catalogue.Orbit022
