/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.CompletedStar

/-! # Completed-star catalogue orbit 016

Generated by scripts/import_completed_star_catalogue.py from certificate SHA256
4dbb85f7bef9f06a6b4701c7bd611c60507ecedfcf83c46b2c6b1a44828f513d.
Literal data only; acceptance is checked by ordinary Lean decision reduction.
This file does not assert orbit or labelled-universe coverage.
-/

namespace Gallai.Certificate.CompletedStar.Catalogue.Orbit016

open Star.Vertex

/-- The original five rows of this representative. -/
def state : State := ![3, 0, 3, 0, 15]

/-- Ordered replacement words at each of the ten interfaces. -/
def replacements : Fin 10 → List (List Star.Vertex) :=
  ![[[p, x, q], [r, d, s]],
    [[p, d, r], [q, x, d, s]],
    [[p, d, s], [q, x, d, r]],
    [[p, b], [q, x, a], [r, d, s]],
    [[p, b], [r, d], [q, x, d, s]],
    [[p, b], [s, d], [q, x, d, r]],
    [[q, b], [r, d], [p, x, d, s]],
    [[q, b], [s, d], [p, x, d, r]],
    [[r, d], [s, d], [p, x, q]],
    [[p, b], [q, b], [r, d], [s, d, x, a]]]

/-- Added words, preserving distinct occurrences. -/
def added : Fin 10 → List (List Star.Vertex) :=
  ![[[a, b, x, d, p], [a, x, c, d, q, b, p]],
    [[a, b, x, c], [a, x, p, b, q, d, c]],
    [[a, b, x, c], [a, x, p, b, q, d, c]],
    [[a, b, x, d, c], [b, q, d, p, x, c]],
    [[a, b, x, c, d], [a, x, p, d, q, b]],
    [[a, b, x, c, d], [a, x, p, d, q, b]],
    [[a, b, x, c, d], [a, x, q, d, p, b]],
    [[a, b, x, c, d], [a, x, q, d, p, b]],
    [[a, b, x, d, p], [a, x, c, d, q, b, p]],
    [[a, b, x, c, d, p], [d, q, x, p]]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every interface at this representative meets the actual finite contract. -/
theorem accepted (i : Fin 10) : AcceptedRecord state i (replacements i) (added i) := by
  revert i
  decide

end Gallai.Certificate.CompletedStar.Catalogue.Orbit016
