/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.CompletedStar

/-! # Completed-star catalogue orbit 050

Generated by scripts/import_completed_star_catalogue.py from certificate SHA256
4dbb85f7bef9f06a6b4701c7bd611c60507ecedfcf83c46b2c6b1a44828f513d.
Literal data only; acceptance is checked by ordinary Lean decision reduction.
This file does not assert orbit or labelled-universe coverage.
-/

namespace Gallai.Certificate.CompletedStar.Catalogue.Orbit050

open Star.Vertex

/-- The original five rows of this representative. -/
def state : State := ![15, 0, 0, 15, 15]

/-- Ordered replacement words at each of the ten interfaces. -/
def replacements : Fin 10 → List (List Star.Vertex) :=
  ![[[p, x, q], [r, c, d, x, s]],
    [[p, x, r], [q, c, d, x, s]],
    [[p, x, s], [q, c, d, x, r]],
    [[p, c], [q, x, a], [r, c, d, x, s]],
    [[p, c], [r, x, a], [q, c, d, x, s]],
    [[p, c], [s, x, a], [q, c, d, x, r]],
    [[q, c], [r, x, a], [p, c, d, x, s]],
    [[q, c], [s, x, a], [p, c, d, x, r]],
    [[r, c], [s, x, a], [p, c, d, x, q]],
    [[p, c], [q, c], [r, x, a], [s, d, x, c]]]

/-- Added words, preserving distinct occurrences. -/
def added : Fin 10 → List (List Star.Vertex) :=
  ![[[a, b, x, c, p, d, q], [a, x, r, d, s, c, q]],
    [[a, b, x, c, p, d, r], [a, x, q, d, s, c, r]],
    [[a, b, x, c, p, d, r], [a, x, q, d, s, c, r]],
    [[a, b, x, c, q, d, p], [c, s, d, r, x, p]],
    [[a, b, x, c, r, d, p], [c, s, d, q, x, p]],
    [[a, b, x, c, r, d, p], [c, s, d, q, x, p]],
    [[a, b, x, c, r, d, p], [c, s, d, q, x, p]],
    [[a, b, x, c, r, d, p], [c, s, d, q, x, p]],
    [[a, b, x, c, q, d, p], [c, s, d, r, x, p]],
    [[a, b, x, p, d, c, r], [c, s, x, q, d, r]]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every interface at this representative meets the actual finite contract. -/
theorem accepted (i : Fin 10) : AcceptedRecord state i (replacements i) (added i) := by
  revert i
  decide

end Gallai.Certificate.CompletedStar.Catalogue.Orbit050
