/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.CompletedStar

/-! # Completed-star catalogue orbit 054

Generated by scripts/import_completed_star_catalogue.py from certificate SHA256
4dbb85f7bef9f06a6b4701c7bd611c60507ecedfcf83c46b2c6b1a44828f513d.
Literal data only; acceptance is checked by ordinary Lean decision reduction.
This file does not assert orbit or labelled-universe coverage.
-/

namespace Gallai.Certificate.CompletedStar.Catalogue.Orbit054

open Star.Vertex

/-- The original five rows of this representative. -/
def state : State := ![15, 0, 15, 0, 15]

/-- Ordered replacement words at each of the ten interfaces. -/
def replacements : Fin 10 → List (List Star.Vertex) :=
  ![[[p, x, q], [r, b, x, d, s]],
    [[p, x, r], [q, b, x, d, s]],
    [[p, x, s], [q, b, x, d, r]],
    [[p, b], [q, x, a], [r, b, x, d, s]],
    [[p, b], [r, x, a], [q, b, x, d, s]],
    [[p, b], [s, x, a], [q, b, x, d, r]],
    [[q, b], [r, x, a], [p, b, x, d, s]],
    [[q, b], [s, x, a], [p, b, x, d, r]],
    [[r, b], [s, x, a], [p, b, x, d, q]],
    [[p, b], [q, b], [r, x, a], [s, d, x, b]]]

/-- Added words, preserving distinct occurrences. -/
def added : Fin 10 → List (List Star.Vertex) :=
  ![[[a, b, p, d, c, x, r], [a, x, s, b, q, d, r]],
    [[a, b, p, d, c, x, q], [a, x, s, b, r, d, q]],
    [[a, b, p, d, c, x, q], [a, x, r, b, s, d, q]],
    [[a, b, q, d, c, x, p], [b, s, x, r, d, p]],
    [[a, b, r, d, c, x, p], [b, s, x, q, d, p]],
    [[a, b, r, x, c, d, p], [b, s, d, q, x, p]],
    [[a, b, r, d, c, x, p], [b, s, x, q, d, p]],
    [[a, b, r, x, c, d, p], [b, s, d, q, x, p]],
    [[a, b, q, x, c, d, p], [b, s, d, r, x, p]],
    [[a, b, r, d, c, x, p], [b, s, x, q, d, p]]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every interface at this representative meets the actual finite contract. -/
theorem accepted (i : Fin 10) : AcceptedRecord state i (replacements i) (added i) := by
  revert i
  decide

end Gallai.Certificate.CompletedStar.Catalogue.Orbit054
