/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.CompletedStar

/-! # Completed-star catalogue orbit 034

Generated by scripts/import_completed_star_catalogue.py from certificate SHA256
4dbb85f7bef9f06a6b4701c7bd611c60507ecedfcf83c46b2c6b1a44828f513d.
Literal data only; acceptance is checked by ordinary Lean decision reduction.
This file does not assert orbit or labelled-universe coverage.
-/

namespace Gallai.Certificate.CompletedStar.Catalogue.Orbit034

open Star.Vertex

/-- The original five rows of this representative. -/
def state : State := ![3, 3, 12, 5, 6]

/-- Ordered replacement words at each of the ten interfaces. -/
def replacements : Fin 10 → List (List Star.Vertex) :=
  ![[[p, a, q], [r, c, x, b, s]],
    [[p, c, r], [q, x, b, s]],
    [[p, a, b, s], [q, x, b, r]],
    [[p, a], [q, a], [r, c, x, b, s]],
    [[p, a], [r, b], [q, x, b, s]],
    [[p, a], [s, b], [q, x, b, r]],
    [[q, a], [r, b], [p, x, b, s]],
    [[q, a], [s, b], [p, x, b, r]],
    [[r, b], [s, b], [p, x, q]],
    [[p, a], [q, a], [r, b], [s, b, x, c]]]

/-- Added words, preserving distinct occurrences. -/
def added : Fin 10 → List (List Star.Vertex) :=
  ![[[b, a, x, d, c], [b, r, d, q, x, p, c]],
    [[b, a, x, d, c], [b, r, d, q, a, p, x, c]],
    [[a, q, d, c, x, p], [a, x, d, r, c, p]],
    [[b, a, x, d, c], [b, r, d, q, x, p, c]],
    [[b, a, x, c, d, r], [a, q, d, x, p, c, r]],
    [[b, a, x, c, d, r], [a, q, d, x, p, c, r]],
    [[b, a, x, c, d, q], [a, p, c, r, d, x, q]],
    [[b, a, x, c, d, q], [a, p, c, r, d, x, q]],
    [[b, a, x, c, d, q], [b, x, d, r, c, p, a, q]],
    [[b, a, x, d, c, p], [c, r, d, q, x, p]]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every interface at this representative meets the actual finite contract. -/
theorem accepted (i : Fin 10) : AcceptedRecord state i (replacements i) (added i) := by
  revert i
  decide

end Gallai.Certificate.CompletedStar.Catalogue.Orbit034
