/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.CompletedStar

/-! # Completed-star catalogue orbit 042

Generated by scripts/import_completed_star_catalogue.py from certificate SHA256
4dbb85f7bef9f06a6b4701c7bd611c60507ecedfcf83c46b2c6b1a44828f513d.
Literal data only; acceptance is checked by ordinary Lean decision reduction.
This file does not assert orbit or labelled-universe coverage.
-/

namespace Gallai.Certificate.CompletedStar.Catalogue.Orbit042

open Star.Vertex

/-- The original five rows of this representative. -/
def state : State := ![3, 5, 9, 12, 12]

/-- Ordered replacement words at each of the ten interfaces. -/
def replacements : Fin 10 → List (List Star.Vertex) :=
  ![[[p, x, q], [r, c, s]],
    [[p, a, r], [q, x, b, s]],
    [[p, b, s], [q, x, a, r]],
    [[p, a], [q, x], [r, a, x, b, s]],
    [[p, a], [r, a], [q, x, b, s]],
    [[p, a], [s, b], [q, x, a, r]],
    [[q, x], [r, a], [p, x, c, s]],
    [[q, x], [s, b], [p, x, c, r]],
    [[r, a], [s, b], [p, x, q]],
    [[p, a], [q, x], [r, a], [s, b, x]]]

/-- Added words, preserving distinct occurrences. -/
def added : Fin 10 → List (List Star.Vertex) :=
  ![[[c, d, x, a, b, p], [c, x, b, s, d, r, a, p]],
    [[b, a, x, c, d, r], [b, p, x, d, s, c, r]],
    [[a, b, x, c, d, r], [a, p, x, d, s, c, r]],
    [[a, b, p, x, c, d, r], [r, c, s, d, x]],
    [[b, a, x, c, d, r], [b, p, x, d, s, c, r]],
    [[a, b, x, c, d, r], [b, p, x, d, s, c, r]],
    [[a, b, x, d, c], [c, r, d, s, b, p, a, x]],
    [[b, a, x, d, c], [c, s, d, r, a, p, b, x]],
    [[a, b, x, c, d, r], [b, p, a, x, d, s, c, r]],
    [[b, a, x, c, d, r], [b, p, x, d, s, c, r]]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every interface at this representative meets the actual finite contract. -/
theorem accepted (i : Fin 10) : AcceptedRecord state i (replacements i) (added i) := by
  revert i
  decide

end Gallai.Certificate.CompletedStar.Catalogue.Orbit042
