/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.CompletedStar

/-! # Completed-star catalogue orbit 041

Generated by scripts/import_completed_star_catalogue.py from certificate SHA256
4dbb85f7bef9f06a6b4701c7bd611c60507ecedfcf83c46b2c6b1a44828f513d.
Literal data only; acceptance is checked by ordinary Lean decision reduction.
This file does not assert orbit or labelled-universe coverage.
-/

namespace Gallai.Certificate.CompletedStar.Catalogue.Orbit041

open Star.Vertex

/-- The original five rows of this representative. -/
def state : State := ![3, 5, 6, 5, 10]

/-- Ordered replacement words at each of the ten interfaces. -/
def replacements : Fin 10 → List (List Star.Vertex) :=
  ![[[p, x, q], [r, c, d, s]],
    [[p, a, r], [q, x, d, s]],
    [[p, c, d, s], [q, x, a, r]],
    [[p, a], [q, b], [r, a, x, d, s]],
    [[p, a], [r, a], [q, x, d, s]],
    [[p, a], [s, d], [q, x, a, r]],
    [[q, b], [r, a], [p, x, d, s]],
    [[q, b], [s, d], [p, x, a, r]],
    [[r, a], [s, d], [p, x, q]],
    [[p, a], [q, b], [r, a], [s, d, x, a]]]

/-- Added words, preserving distinct occurrences. -/
def added : Fin 10 → List (List Star.Vertex) :=
  ![[[c, x, a, b, q], [c, p, a, r, b, x, d, q]],
    [[a, b, x, c, d], [a, x, p, c, r, b, q, d]],
    [[a, b, x, c], [a, p, x, d, q, b, r, c]],
    [[a, b, x, c, d], [b, r, c, p, x, q, d]],
    [[a, b, x, c, d], [a, x, p, c, r, b, q, d]],
    [[a, b, x, c, d, q], [d, x, p, c, r, b, q]],
    [[a, b, x, c, d], [b, r, c, p, a, x, q, d]],
    [[a, b, r, c, x, d], [a, p, c, d, q, x, b]],
    [[a, b, x, c, d, q], [d, x, a, p, c, r, b, q]],
    [[a, b, x, c, d], [b, r, c, p, x, q, d]]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every interface at this representative meets the actual finite contract. -/
theorem accepted (i : Fin 10) : AcceptedRecord state i (replacements i) (added i) := by
  revert i
  decide

end Gallai.Certificate.CompletedStar.Catalogue.Orbit041
