/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.CompletedStar

/-! # Completed-star catalogue orbit 063

Generated by scripts/import_completed_star_catalogue.py from certificate SHA256
4dbb85f7bef9f06a6b4701c7bd611c60507ecedfcf83c46b2c6b1a44828f513d.
Literal data only; acceptance is checked by ordinary Lean decision reduction.
This file does not assert orbit or labelled-universe coverage.
-/

namespace Gallai.Certificate.CompletedStar.Catalogue.Orbit063

open Star.Vertex

/-- The original five rows of this representative. -/
def state : State := ![15, 3, 12, 3, 12]

/-- Ordered replacement words at each of the ten interfaces. -/
def replacements : Fin 10 → List (List Star.Vertex) :=
  ![[[p, x, q], [r, x, s]],
    [[p, x, r], [q, x, s]],
    [[p, x, s], [q, x, r]],
    [[p, a], [q, x, a], [r, x, s]],
    [[p, a], [r, x, a], [q, x, s]],
    [[p, a], [s, x, a], [q, x, r]],
    [[q, a], [r, x, a], [p, x, s]],
    [[q, a], [s, x, a], [p, x, r]],
    [[r, b], [s, x, a], [p, x, q]],
    [[p, a], [q, a], [r, x, a], [s, x, b]]]

/-- Added words, preserving distinct occurrences. -/
def added : Fin 10 → List (List Star.Vertex) :=
  ![[[p, a, b, x, c, d, r], [p, c, q, a, x, d, s, b, r]],
    [[p, a, b, x, c, d, r], [p, c, q, a, x, d, s, b, r]],
    [[p, a, b, x, c, d, r], [p, c, q, a, x, d, s, b, r]],
    [[a, b, x, c, d, r], [a, q, c, p, x, d, s, b, r]],
    [[a, b, x, c, d, r], [a, q, c, p, x, d, s, b, r]],
    [[a, b, x, c, d, r], [a, q, c, p, x, d, s, b, r]],
    [[a, b, x, c, d, r], [a, p, c, q, x, d, s, b, r]],
    [[a, b, x, c, d, r], [a, p, c, q, x, d, s, b, r]],
    [[a, b, x, d, c, p], [b, s, d, r, x, c, q, a, p]],
    [[a, b, r, d, c, x, p], [b, s, d, x, q, c, p]]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every interface at this representative meets the actual finite contract. -/
theorem accepted (i : Fin 10) : AcceptedRecord state i (replacements i) (added i) := by
  revert i
  decide

end Gallai.Certificate.CompletedStar.Catalogue.Orbit063
