/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.CompletedStar

/-! # Completed-star catalogue orbit 061

Generated by scripts/import_completed_star_catalogue.py from certificate SHA256
4dbb85f7bef9f06a6b4701c7bd611c60507ecedfcf83c46b2c6b1a44828f513d.
Literal data only; acceptance is checked by ordinary Lean decision reduction.
This file does not assert orbit or labelled-universe coverage.
-/

namespace Gallai.Certificate.CompletedStar.Catalogue.Orbit061

open Star.Vertex

/-- The original five rows of this representative. -/
def state : State := ![15, 3, 5, 9, 15]

/-- Ordered replacement words at each of the ten interfaces. -/
def replacements : Fin 10 → List (List Star.Vertex) :=
  ![[[p, x, q], [r, d, x, s]],
    [[p, x, r], [q, d, x, s]],
    [[p, x, s], [q, d, x, r]],
    [[p, a], [q, x, a], [r, d, x, s]],
    [[p, a], [r, x, a], [q, d, x, s]],
    [[p, a], [s, x, a], [q, d, x, r]],
    [[q, a], [r, x, a], [p, d, x, s]],
    [[q, a], [s, x, a], [p, d, x, r]],
    [[r, b], [s, x, a], [p, d, x, q]],
    [[p, a], [q, a], [r, x, a], [s, d, x, b]]]

/-- Added words, preserving distinct occurrences. -/
def added : Fin 10 → List (List Star.Vertex) :=
  ![[[q, a, b, p, d, c, x, r], [q, d, s, c, p, a, x, b, r]],
    [[q, a, b, x, c, p, d, s], [q, x, a, p, b, r, d, c, s]],
    [[q, a, b, x, c, p, d, s], [q, x, a, p, b, r, d, c, s]],
    [[a, b, p, d, c, x, r], [a, q, d, s, c, p, x, b, r]],
    [[a, b, p, x, c, d, s], [a, q, x, b, r, d, p, c, s]],
    [[a, b, p, x, c, d, s], [a, q, x, b, r, d, p, c, s]],
    [[a, b, p, x, c, d, q], [a, p, c, s, d, r, b, x, q]],
    [[a, b, p, x, c, d, q], [a, p, c, s, d, r, b, x, q]],
    [[a, b, p, x, c, d, q], [b, x, r, d, s, c, p, a, q]],
    [[a, b, p, d, c, x, s], [b, r, d, q, x, p, c, s]]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every interface at this representative meets the actual finite contract. -/
theorem accepted (i : Fin 10) : AcceptedRecord state i (replacements i) (added i) := by
  revert i
  decide

end Gallai.Certificate.CompletedStar.Catalogue.Orbit061
