/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.CompletedStar

/-! # Completed-star catalogue orbit 010

Generated by scripts/import_completed_star_catalogue.py from certificate SHA256
4dbb85f7bef9f06a6b4701c7bd611c60507ecedfcf83c46b2c6b1a44828f513d.
Literal data only; acceptance is checked by ordinary Lean decision reduction.
This file does not assert orbit or labelled-universe coverage.
-/

namespace Gallai.Certificate.CompletedStar.Catalogue.Orbit010

open Star.Vertex

/-- The original five rows of this representative. -/
def state : State := ![0, 3, 5, 6, 15]

/-- Ordered replacement words at each of the ten interfaces. -/
def replacements : Fin 10 → List (List Star.Vertex) :=
  ![[[p, a, q], [r, d, s]],
    [[p, b, r], [q, d, s]],
    [[p, d, s], [q, c, r]],
    [[p, a], [q, a], [r, d, s]],
    [[p, a], [r, b], [q, d, s]],
    [[p, a], [s, d], [q, d, r]],
    [[q, a], [r, b], [p, d, s]],
    [[q, a], [s, d], [p, d, r]],
    [[r, b], [s, d], [p, d, q]],
    [[p, a], [q, a], [r, b], [s, d, c]]]

/-- Added words, preserving distinct occurrences. -/
def added : Fin 10 → List (List Star.Vertex) :=
  ![[[a, b, x, c, d, p], [a, x, d, q, c, r, b, p]],
    [[b, a, x, c, d, p], [b, x, d, r, c, q, a, p]],
    [[c, d, x, a, b, p], [c, x, b, r, d, q, a, p]],
    [[a, b, x, c, d, p], [a, x, d, q, c, r, b, p]],
    [[a, b, x, c, d, r], [b, p, d, x, a, q, c, r]],
    [[a, b, x, c, d, p], [d, x, a, q, c, r, b, p]],
    [[a, b, x, c, d, q], [b, p, a, x, d, r, c, q]],
    [[a, b, x, c, d, q], [d, x, a, p, b, r, c, q]],
    [[b, a, x, c, d, r], [d, x, b, p, a, q, c, r]],
    [[a, b, x, d, q, c], [a, x, c, r, d, p, b]]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every interface at this representative meets the actual finite contract. -/
theorem accepted (i : Fin 10) : AcceptedRecord state i (replacements i) (added i) := by
  revert i
  decide

end Gallai.Certificate.CompletedStar.Catalogue.Orbit010
