/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.CompletedStar

/-! # Completed-star catalogue orbit 044

Generated by scripts/import_completed_star_catalogue.py from certificate SHA256
4dbb85f7bef9f06a6b4701c7bd611c60507ecedfcf83c46b2c6b1a44828f513d.
Literal data only; acceptance is checked by ordinary Lean decision reduction.
This file does not assert orbit or labelled-universe coverage.
-/

namespace Gallai.Certificate.CompletedStar.Catalogue.Orbit044

open Star.Vertex

/-- The original five rows of this representative. -/
def state : State := ![3, 5, 10, 12, 15]

/-- Ordered replacement words at each of the ten interfaces. -/
def replacements : Fin 10 → List (List Star.Vertex) :=
  ![[[p, d, q], [r, a, x, b, s]],
    [[p, a, r], [q, x, d, s]],
    [[p, d, s], [q, x, a, r]],
    [[p, a], [q, b], [r, a, x, d, s]],
    [[p, a], [r, a], [q, x, d, s]],
    [[p, a], [s, b], [q, x, d, r]],
    [[q, b], [r, a], [p, x, d, s]],
    [[q, b], [s, b], [p, x, d, r]],
    [[r, a], [s, b], [p, d, x, q]],
    [[p, a], [q, b], [r, a], [s, d, x, a]]]

/-- Added words, preserving distinct occurrences. -/
def added : Fin 10 → List (List Star.Vertex) :=
  ![[[a, b, q, x, c, d, r], [a, p, x, d, s, c, r]],
    [[a, b, x, c, d, q], [a, x, p, d, r, c, s, b, q]],
    [[a, b, x, c, d, q], [a, p, x, d, r, c, s, b, q]],
    [[a, b, x, c, d, p], [b, s, c, r, d, q, x, p]],
    [[a, b, x, c, d, q], [a, x, p, d, r, c, s, b, q]],
    [[a, b, x, c, d, p], [b, q, d, s, c, r, a, x, p]],
    [[a, b, x, c, d, p], [b, s, c, r, d, q, x, a, p]],
    [[b, a, x, c, d, p], [b, x, q, d, s, c, r, a, p]],
    [[b, a, x, c, d, r], [a, p, x, b, q, d, s, c, r]],
    [[a, b, x, c, d, p], [b, s, c, r, d, q, x, p]]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every interface at this representative meets the actual finite contract. -/
theorem accepted (i : Fin 10) : AcceptedRecord state i (replacements i) (added i) := by
  revert i
  decide

end Gallai.Certificate.CompletedStar.Catalogue.Orbit044
