/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.CompletedStar

/-! # Completed-star catalogue orbit 011

Generated by scripts/import_completed_star_catalogue.py from certificate SHA256
4dbb85f7bef9f06a6b4701c7bd611c60507ecedfcf83c46b2c6b1a44828f513d.
Literal data only; acceptance is checked by ordinary Lean decision reduction.
This file does not assert orbit or labelled-universe coverage.
-/

namespace Gallai.Certificate.CompletedStar.Catalogue.Orbit011

open Star.Vertex

/-- The original five rows of this representative. -/
def state : State := ![0, 3, 12, 15, 15]

/-- Ordered replacement words at each of the ten interfaces. -/
def replacements : Fin 10 → List (List Star.Vertex) :=
  ![[[p, a, q], [r, c, d, s]],
    [[p, c, r], [q, d, s]],
    [[p, c, s], [q, d, r]],
    [[p, a], [q, a], [r, c, d, s]],
    [[p, a], [r, b], [q, c, d, s]],
    [[p, a], [s, b], [q, c, d, r]],
    [[q, a], [r, b], [p, c, d, s]],
    [[q, a], [s, b], [p, c, d, r]],
    [[r, b], [s, b], [p, c, d, q]],
    [[p, a], [q, a], [r, b], [s, c, d, x]]]

/-- Added words, preserving distinct occurrences. -/
def added : Fin 10 → List (List Star.Vertex) :=
  ![[[a, b, r, d, x, c, p], [a, x, b, s, c, q, d, p]],
    [[p, a, b, x, c, d, r], [p, d, x, a, q, c, s, b, r]],
    [[p, a, b, x, c, d, s], [p, d, x, a, q, c, r, b, s]],
    [[a, b, r, d, x, c, p], [a, x, b, s, c, q, d, p]],
    [[a, b, s, c, x, d, p], [b, x, a, q, d, r, c, p]],
    [[a, b, r, c, x, d, p], [b, x, a, q, d, s, c, p]],
    [[a, b, s, c, x, d, q], [b, x, a, p, d, r, c, q]],
    [[a, b, r, c, x, d, q], [b, x, a, p, d, s, c, q]],
    [[b, a, p, d, x, c, r], [b, x, a, q, c, s, d, r]],
    [[b, a, x, c, p, d, q], [q, c, r, d, s, b, x]]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every interface at this representative meets the actual finite contract. -/
theorem accepted (i : Fin 10) : AcceptedRecord state i (replacements i) (added i) := by
  revert i
  decide

end Gallai.Certificate.CompletedStar.Catalogue.Orbit011
