/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.CompletedStar

/-! # Completed-star catalogue orbit 025

Generated by scripts/import_completed_star_catalogue.py from certificate SHA256
4dbb85f7bef9f06a6b4701c7bd611c60507ecedfcf83c46b2c6b1a44828f513d.
Literal data only; acceptance is checked by ordinary Lean decision reduction.
This file does not assert orbit or labelled-universe coverage.
-/

namespace Gallai.Certificate.CompletedStar.Catalogue.Orbit025

open Star.Vertex

/-- The original five rows of this representative. -/
def state : State := ![3, 0, 12, 12, 12]

/-- Ordered replacement words at each of the ten interfaces. -/
def replacements : Fin 10 → List (List Star.Vertex) :=
  ![[[p, x, q], [r, b, s]],
    [[p, x, b, r], [q, x, c, s]],
    [[p, x, b, s], [q, x, c, r]],
    [[p, x], [q, x], [r, b, s]],
    [[p, x], [r, b], [q, x, b, s]],
    [[p, x], [s, b], [q, x, b, r]],
    [[q, x], [r, b], [p, x, b, s]],
    [[q, x], [s, b], [p, x, b, r]],
    [[r, b], [s, b], [p, x, q]],
    [[p, x], [q, x], [r, b], [s, b]]]

/-- Added words, preserving distinct occurrences. -/
def added : Fin 10 → List (List Star.Vertex) :=
  ![[[a, b, x, c, d, r], [a, x, d, s, c, r]],
    [[a, b, s, d, c], [a, x, d, r, c]],
    [[a, b, r, d, c], [a, x, d, s, c]],
    [[a, b, x, c, d, r], [a, x, d, s, c, r]],
    [[b, a, x, c, d, r], [r, c, s, d, x]],
    [[b, a, x, c, d, r], [r, c, s, d, x]],
    [[b, a, x, c, d, r], [r, c, s, d, x]],
    [[b, a, x, c, d, r], [r, c, s, d, x]],
    [[a, b, x, c, d, r], [a, x, d, s, c, r]],
    [[a, b, x, c, d, r], [a, x, d, s, c, r]]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every interface at this representative meets the actual finite contract. -/
theorem accepted (i : Fin 10) : AcceptedRecord state i (replacements i) (added i) := by
  revert i
  decide

end Gallai.Certificate.CompletedStar.Catalogue.Orbit025
