/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.CompletedStar

/-! # Completed-star catalogue orbit 065

Generated by scripts/import_completed_star_catalogue.py from certificate SHA256
4dbb85f7bef9f06a6b4701c7bd611c60507ecedfcf83c46b2c6b1a44828f513d.
Literal data only; acceptance is checked by ordinary Lean decision reduction.
This file does not assert orbit or labelled-universe coverage.
-/

namespace Gallai.Certificate.CompletedStar.Catalogue.Orbit065

open Star.Vertex

/-- The original five rows of this representative. -/
def state : State := ![15, 3, 15, 3, 15]

/-- Ordered replacement words at each of the ten interfaces. -/
def replacements : Fin 10 → List (List Star.Vertex) :=
  ![[[p, x, q], [r, b, x, d, s]],
    [[p, x, r], [q, b, x, d, s]],
    [[p, x, s], [q, b, x, d, r]],
    [[p, a], [q, x, a], [r, b, x, d, s]],
    [[p, a], [r, x, a], [q, b, x, d, s]],
    [[p, a], [s, x, a], [q, b, x, d, r]],
    [[q, a], [r, x, a], [p, b, x, d, s]],
    [[q, a], [s, x, a], [p, b, x, d, r]],
    [[r, b], [s, x, a], [p, b, x, d, q]],
    [[p, a], [q, a], [r, x, a], [s, b, x, d, c]]]

/-- Added words, preserving distinct occurrences. -/
def added : Fin 10 → List (List Star.Vertex) :=
  ![[[r, d, p, a, b, q, c, x, s], [r, x, a, q, d, c, p, b, s]],
    [[r, b, a, p, d, c, q, x, s], [r, d, q, a, x, c, p, b, s]],
    [[r, b, a, p, c, x, q, d, s], [r, x, a, q, c, d, p, b, s]],
    [[a, b, p, d, q, c, x, r], [a, q, b, s, x, p, c, d, r]],
    [[a, b, p, c, d, q, x, s], [a, q, c, x, p, d, r, b, s]],
    [[a, b, p, c, d, q, x, r], [a, q, c, x, p, d, s, b, r]],
    [[a, b, q, c, d, p, x, s], [a, p, c, x, q, d, r, b, s]],
    [[a, b, q, c, d, p, x, r], [a, p, c, x, q, d, s, b, r]],
    [[a, b, q, c, x, p, d, r], [b, s, d, c, p, a, q, x, r]],
    [[a, b, p, c, x, q, d, s], [c, q, b, r, d, p, x, s]]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every interface at this representative meets the actual finite contract. -/
theorem accepted (i : Fin 10) : AcceptedRecord state i (replacements i) (added i) := by
  revert i
  decide

end Gallai.Certificate.CompletedStar.Catalogue.Orbit065
