/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.CompletedStar

/-! # Completed-star catalogue orbit 047

Generated by scripts/import_completed_star_catalogue.py from certificate SHA256
4dbb85f7bef9f06a6b4701c7bd611c60507ecedfcf83c46b2c6b1a44828f513d.
Literal data only; acceptance is checked by ordinary Lean decision reduction.
This file does not assert orbit or labelled-universe coverage.
-/

namespace Gallai.Certificate.CompletedStar.Catalogue.Orbit047

open Star.Vertex

/-- The original five rows of this representative. -/
def state : State := ![3, 5, 15, 9, 15]

/-- Ordered replacement words at each of the ten interfaces. -/
def replacements : Fin 10 → List (List Star.Vertex) :=
  ![[[p, b, q], [r, a, x, d, s]],
    [[p, a, r], [q, b, x, d, s]],
    [[p, b, s], [q, x, d, r]],
    [[p, a], [q, b], [r, b, x, d, s]],
    [[p, a], [r, a], [q, b, x, d, s]],
    [[p, a], [s, b], [q, b, x, d, r]],
    [[q, b], [r, a], [p, b, x, d, s]],
    [[q, b], [s, b], [p, x, d, r]],
    [[r, a], [s, b], [p, b, x, d, q]],
    [[p, a], [q, b], [r, a], [s, d, x, b]]]

/-- Added words, preserving distinct occurrences. -/
def added : Fin 10 → List (List Star.Vertex) :=
  ![[[a, b, x, c, p, d, r], [a, p, x, q, d, c, s, b, r]],
    [[a, b, p, d, c, x, q], [a, x, p, c, s, b, r, d, q]],
    [[q, b, a, x, p, c, d, s], [q, d, p, a, r, b, x, c, s]],
    [[a, b, p, d, c, x, q], [b, s, c, p, x, a, r, d, q]],
    [[a, b, p, d, c, x, q], [a, x, p, c, s, b, r, d, q]],
    [[a, b, p, d, c, x, q], [b, r, a, x, p, c, s, d, q]],
    [[b, a, p, d, c, x, q], [a, x, p, c, s, b, r, d, q]],
    [[q, d, p, a, b, x, c, s], [q, x, a, r, b, p, c, d, s]],
    [[b, a, p, d, c, x, q], [a, x, p, c, s, d, r, b, q]],
    [[a, b, p, d, c, x, q], [a, x, p, c, s, b, r, d, q]]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every interface at this representative meets the actual finite contract. -/
theorem accepted (i : Fin 10) : AcceptedRecord state i (replacements i) (added i) := by
  revert i
  decide

end Gallai.Certificate.CompletedStar.Catalogue.Orbit047
