/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.CompletedStar

/-! # Completed-star catalogue orbit 007

Generated by scripts/import_completed_star_catalogue.py from certificate SHA256
4dbb85f7bef9f06a6b4701c7bd611c60507ecedfcf83c46b2c6b1a44828f513d.
Literal data only; acceptance is checked by ordinary Lean decision reduction.
This file does not assert orbit or labelled-universe coverage.
-/

namespace Gallai.Certificate.CompletedStar.Catalogue.Orbit007

open Star.Vertex

/-- The original five rows of this representative. -/
def state : State := ![0, 3, 3, 3, 12]

/-- Ordered replacement words at each of the ten interfaces. -/
def replacements : Fin 10 → List (List Star.Vertex) :=
  ![[[p, a, q], [r, d, s]],
    [[p, c, d, r], [q, a, x, d, s]],
    [[p, c, d, s], [q, a, x, d, r]],
    [[p, a], [q, a], [r, d, s]],
    [[p, a], [r, d], [q, c, d, s]],
    [[p, a], [s, d], [q, c, d, r]],
    [[q, a], [r, d], [p, c, d, s]],
    [[q, a], [s, d], [p, c, d, r]],
    [[r, d], [s, d], [p, a, q]],
    [[p, a], [q, a], [r, d], [s, d]]]

/-- Added words, preserving distinct occurrences. -/
def added : Fin 10 → List (List Star.Vertex) :=
  ![[[a, b, x, c, p], [a, x, d, c, q, b, p]],
    [[a, b, q], [a, p, b, x, c, q]],
    [[a, b, q], [a, p, b, x, c, q]],
    [[a, b, x, c, p], [a, x, d, c, q, b, p]],
    [[a, b, x, c], [c, p, b, q, a, x, d]],
    [[a, b, x, c], [c, p, b, q, a, x, d]],
    [[a, b, x, c], [c, q, b, p, a, x, d]],
    [[a, b, x, c], [c, q, b, p, a, x, d]],
    [[a, b, x, c, p], [a, x, d, c, q, b, p]],
    [[a, b, x, c, p], [a, x, d, c, q, b, p]]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every interface at this representative meets the actual finite contract. -/
theorem accepted (i : Fin 10) : AcceptedRecord state i (replacements i) (added i) := by
  revert i
  decide

end Gallai.Certificate.CompletedStar.Catalogue.Orbit007
