/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.CompletedStar

/-! # Completed-star catalogue orbit 030

Generated by scripts/import_completed_star_catalogue.py from certificate SHA256
4dbb85f7bef9f06a6b4701c7bd611c60507ecedfcf83c46b2c6b1a44828f513d.
Literal data only; acceptance is checked by ordinary Lean decision reduction.
This file does not assert orbit or labelled-universe coverage.
-/

namespace Gallai.Certificate.CompletedStar.Catalogue.Orbit030

open Star.Vertex

/-- The original five rows of this representative. -/
def state : State := ![3, 3, 3, 5, 9]

/-- Ordered replacement words at each of the ten interfaces. -/
def replacements : Fin 10 → List (List Star.Vertex) :=
  ![[[p, a, q], [r, c, x, d, s]],
    [[p, c, r], [q, x, d, s]],
    [[p, d, s], [q, x, c, r]],
    [[p, a], [q, a], [r, c, x, d, s]],
    [[p, a], [r, c], [q, x, d, s]],
    [[p, a], [s, d], [q, x, c, r]],
    [[q, a], [r, c], [p, x, d, s]],
    [[q, a], [s, d], [p, x, c, r]],
    [[r, c], [s, d], [p, x, q]],
    [[p, a], [q, a], [r, c], [s, d, x, a]]]

/-- Added words, preserving distinct occurrences. -/
def added : Fin 10 → List (List Star.Vertex) :=
  ![[[a, b, x, p, c], [a, x, q, b, p, d, c]],
    [[c, x, p, a, b, q], [c, d, p, b, x, a, q]],
    [[c, p, x, a, b, q], [c, d, x, b, p, a, q]],
    [[a, b, x, p, c], [a, x, q, b, p, d, c]],
    [[a, b, x, p, c, d], [c, x, a, q, b, p, d]],
    [[a, b, x, p, d, c], [c, p, b, q, a, x, d]],
    [[a, b, p, c, x, q], [c, d, p, a, x, b, q]],
    [[a, b, p, d, x, q], [d, c, p, a, x, b, q]],
    [[c, p, d, x, a, b, q], [d, c, x, b, p, a, q]],
    [[a, b, p, c, x, q], [c, d, p, x, b, q]]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every interface at this representative meets the actual finite contract. -/
theorem accepted (i : Fin 10) : AcceptedRecord state i (replacements i) (added i) := by
  revert i
  decide

end Gallai.Certificate.CompletedStar.Catalogue.Orbit030
