/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.CompletedStar

/-! # Completed-star catalogue orbit 023

Generated by scripts/import_completed_star_catalogue.py from certificate SHA256
4dbb85f7bef9f06a6b4701c7bd611c60507ecedfcf83c46b2c6b1a44828f513d.
Literal data only; acceptance is checked by ordinary Lean decision reduction.
This file does not assert orbit or labelled-universe coverage.
-/

namespace Gallai.Certificate.CompletedStar.Catalogue.Orbit023

open Star.Vertex

/-- The original five rows of this representative. -/
def state : State := ![3, 0, 12, 3, 3]

/-- Ordered replacement words at each of the ten interfaces. -/
def replacements : Fin 10 → List (List Star.Vertex) :=
  ![[[p, x, q], [r, b, s]],
    [[p, x, b, r], [q, x, a, b, s]],
    [[p, x, b, s], [q, x, a, b, r]],
    [[p, c], [q, x, a], [r, b, s]],
    [[p, c], [r, b], [q, x, b, s]],
    [[p, c], [s, b], [q, x, b, r]],
    [[q, c], [r, b], [p, x, b, s]],
    [[q, c], [s, b], [p, x, b, r]],
    [[r, b], [s, b], [p, x, q]],
    [[p, c], [q, c], [r, b], [s, b, x, c]]]

/-- Added words, preserving distinct occurrences. -/
def added : Fin 10 → List (List Star.Vertex) :=
  ![[[a, b, x, c, d, p], [a, x, d, q, c, p]],
    [[p, c, d, q], [p, d, x, c, q]],
    [[p, c, d, q], [p, d, x, c, q]],
    [[a, b, x, c, d, p], [c, q, d, x, p]],
    [[b, a, x, c, d, p], [c, q, d, x, p]],
    [[b, a, x, c, d, p], [c, q, d, x, p]],
    [[b, a, x, c, d, q], [c, p, d, x, q]],
    [[b, a, x, c, d, q], [c, p, d, x, q]],
    [[a, b, x, c, d, p], [a, x, d, q, c, p]],
    [[b, a, x, d, p], [c, d, q, x, p]]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every interface at this representative meets the actual finite contract. -/
theorem accepted (i : Fin 10) : AcceptedRecord state i (replacements i) (added i) := by
  revert i
  decide

end Gallai.Certificate.CompletedStar.Catalogue.Orbit023
