/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.CompletedStar

/-! # Completed-star catalogue orbit 026

Generated by scripts/import_completed_star_catalogue.py from certificate SHA256
4dbb85f7bef9f06a6b4701c7bd611c60507ecedfcf83c46b2c6b1a44828f513d.
Literal data only; acceptance is checked by ordinary Lean decision reduction.
This file does not assert orbit or labelled-universe coverage.
-/

namespace Gallai.Certificate.CompletedStar.Catalogue.Orbit026

open Star.Vertex

/-- The original five rows of this representative. -/
def state : State := ![3, 0, 12, 15, 15]

/-- Ordered replacement words at each of the ten interfaces. -/
def replacements : Fin 10 → List (List Star.Vertex) :=
  ![[[p, c, q], [r, b, x, d, s]],
    [[p, c, r], [q, x, d, s]],
    [[p, c, s], [q, x, d, r]],
    [[p, c], [q, c], [r, b, x, d, s]],
    [[p, c], [r, b], [q, c, x, d, s]],
    [[p, c], [s, b], [q, c, x, d, r]],
    [[q, c], [r, b], [p, c, x, d, s]],
    [[q, c], [s, b], [p, c, x, d, r]],
    [[r, b], [s, b], [p, c, d, x, q]],
    [[p, c], [q, c], [r, b], [s, d, x, a]]]

/-- Added words, preserving distinct occurrences. -/
def added : Fin 10 → List (List Star.Vertex) :=
  ![[[b, a, x, c, d, p], [b, s, c, r, d, q, x, p]],
    [[a, b, x, c, d, q], [a, x, p, d, r, b, s, c, q]],
    [[a, b, x, c, d, q], [a, x, p, d, s, b, r, c, q]],
    [[b, a, x, c, d, p], [b, s, c, r, d, q, x, p]],
    [[a, b, x, p, d, c], [a, x, q, d, r, c, s, b]],
    [[a, b, x, p, d, c], [a, x, q, d, s, c, r, b]],
    [[a, b, x, p, d, c], [a, x, q, d, r, c, s, b]],
    [[a, b, x, p, d, c], [a, x, q, d, s, c, r, b]],
    [[a, b, x, c, q, d, r], [a, x, p, d, s, c, r]],
    [[a, b, x, c, d, p], [b, s, c, r, d, q, x, p]]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every interface at this representative meets the actual finite contract. -/
theorem accepted (i : Fin 10) : AcceptedRecord state i (replacements i) (added i) := by
  revert i
  decide

end Gallai.Certificate.CompletedStar.Catalogue.Orbit026
