/-
Copyright (c) 2026 Idris Ali Shaik.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik (with Codex assistance)
-/
import Gallai.Certificates.CompletedStar

/-! # Completed-star catalogue orbit 043

Generated by scripts/import_completed_star_catalogue.py from certificate SHA256
4dbb85f7bef9f06a6b4701c7bd611c60507ecedfcf83c46b2c6b1a44828f513d.
Literal data only; acceptance is checked by ordinary Lean decision reduction.
This file does not assert orbit or labelled-universe coverage.
-/

namespace Gallai.Certificate.CompletedStar.Catalogue.Orbit043

open Star.Vertex

/-- The original five rows of this representative. -/
def state : State := ![3, 5, 9, 15, 15]

/-- Ordered replacement words at each of the ten interfaces. -/
def replacements : Fin 10 → List (List Star.Vertex) :=
  ![[[p, c, q], [r, a, x, d, s]],
    [[p, a, r], [q, c, x, d, s]],
    [[p, b, s], [q, c, x, d, r]],
    [[p, a], [q, c], [r, c, x, d, s]],
    [[p, a], [r, a], [q, c, x, d, s]],
    [[p, a], [s, b], [q, c, x, d, r]],
    [[q, c], [r, a], [p, c, x, d, s]],
    [[q, c], [s, b], [p, c, x, d, r]],
    [[r, a], [s, b], [p, c, d, x, q]],
    [[p, a], [q, c], [r, a], [s, d, x, c]]]

/-- Added words, preserving distinct occurrences. -/
def added : Fin 10 → List (List Star.Vertex) :=
  ![[[a, b, p, d, c, x, q], [a, p, x, b, s, c, r, d, q]],
    [[a, b, x, p, c, d, r], [a, x, q, d, p, b, s, c, r]],
    [[b, a, x, p, c, d, s], [b, x, q, d, p, a, r, c, s]],
    [[a, b, x, p, c, d, q], [c, s, b, p, d, r, a, x, q]],
    [[a, b, x, p, c, d, r], [a, x, q, d, p, b, s, c, r]],
    [[a, b, x, p, c, d, q], [b, p, d, s, c, r, a, x, q]],
    [[a, b, x, p, d, c, r], [c, s, b, p, a, x, q, d, r]],
    [[b, a, x, p, d, c, r], [c, s, d, q, x, b, p, a, r]],
    [[a, b, p, x, c, q, d, r], [b, x, a, p, d, s, c, r]],
    [[a, b, x, p, c, d, r], [a, x, q, d, p, b, s, c, r]]]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Every interface at this representative meets the actual finite contract. -/
theorem accepted (i : Fin 10) : AcceptedRecord state i (replacements i) (added i) := by
  revert i
  decide

end Gallai.Certificate.CompletedStar.Catalogue.Orbit043
